### ISSUE TITLE
SyntaxError: Unexpected token '.' in `const prevRenderer = extensions.renderers?.[ext.name];`

### ISSUE THREAD

**Issue by priyeshs11** [markedjs/marked#2107] opened 2021-06-16 00:49 UTC
**Marked version:** 2.1.0

**Describe the bug**
Installing the latest version of `marked` causes the error below. Looks like it might be coming from [this PR](https://github.com/markedjs/marked/pull/2043/files), which was merged just some time ago.

```
/home/circleci/project/node_modules/protobufjs/node_modules/marked/src/marked.js:158
          const prevRenderer = extensions.renderers?.[ext.name];
                                                    ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at wrapSafe (internal/modules/cjs/loader.js:902:15)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Object.load (/home/circleci/project/node_modules/protobufjs/node_modules/requizzle/lib/loader.js:105:18)
    at Requizzle.requizzle (/home/circleci/project/node_modules/protobufjs/node_modules/requizzle/lib/requizzle.js:87:31)
    at infectProxy (/home/circleci/project/node_modules/protobufjs/node_modules/requizzle/lib/loader.js:79:31)
    at Module.targetModule.require (/home/circleci/project/node_modules/protobufjs/node_modules/requizzle/lib/loader.js:97:44)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/circleci/project/node_modules/protobufjs/node_modules/jsdoc/lib/jsdoc/util/markdown.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
/home/circleci/project/node_modules/protobufjs/cli/pbts.js:133
                throw err;
```

**To Reproduce**

1. run `yarn`

**Expected behavior**
The library shouldn't throw the above error.

**Comment by pinheadmz** [comment] 2021-06-16 01:10
yep, same here, broke our CI: https://github.com/handshake-org/hsd/runs/2834823661?check_suite_focus=true

**Comment by clamey** [comment] 2021-06-16 01:26
Broke our CI too, via pulling in protobufjs - upgrading to node 14+ seems get past the issue, but we can't do that as a solution for other reasons.

**Comment by UziTech** [comment] 2021-06-16 02:00
duplicate of #2106

**Closed by UziTech** 2021-06-16 02:00 UTC

**Comment by priyeshs11** [comment] 2021-06-16 02:20
> duplicate of #2106

beat me by 1 min 😅  ........anyway, any solutions yet?
