### ISSUE TITLE
Performance Issue, feels like infinite loop

### ISSUE THREAD

**Issue by bwittenberg** [markedjs/marked#2264] opened 2021-11-01 17:15 UTC
**Marked version:**
1.2.5

**Describe the bug**
- Performance issue (feels like infinite loop): `parseInline` requires more than 1 minute to parse a string of underscores.
- NOTE: If the number of underscores is reduced to a certain threshold, `parseInline` will return a value quickly. In the demo, try deleting the underscores one at a time. Also, notice that with an even number of underscores, a value is returned quickly.

<img width="1054" alt="Screen Shot 2021-11-01 at 1 10 59 PM" src="https://user-images.githubusercontent.com/394958/139711650-944f3ffe-ee81-4d5a-9d0e-1d3226373975.png">

**To Reproduce**

Call `parseInline('*_______________________________________________________________________')`

1. [Marked Demo](https://marked.js.org/demo/?text=*___________________________________________________________________________&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.2.5)

**Expected behavior**
- Markdown input is parsed and returned quickly

**Comment by UziTech** [comment] 2021-11-01 18:26
duplicate of #1927

This has been fixed in v2+

**Closed by UziTech** 2021-11-01 18:26 UTC
