### ISSUE TITLE
How can I close render  '_' 

### ISSUE THREAD

**Issue by sandy-shi** [markedjs/marked#1538] opened 2019-08-20 08:29 UTC
I use KateX in this. The '\_' in KateX is a subscript, but marked render it to \<em\>, so the KateX is failed.
How can I close this '\_' render?

**Comment by UziTech** [comment] 2019-08-20 13:42
Anything that is code should be wrapped in backticks (`` ` ``), or indented 4 spaces. Code won't be rendered as markdown.

Could you share some markdown that isn't working correctly?

**Comment by wufeng87** [comment] 2019-08-29 04:59
$$x(t)\delta \left( t-{{t}_{0}} \right)=x\left( {{t}_{0}} \right)\delta \left( t-{{t}_{0}} \right)$$got 
$${x}'\left( t \right)\delta \left( t-{{t}_{0}} \right)+x\left( t \right){\delta }'\left( t-{{t}_{0}} \right)=x\left( {{t}_{0}} \right){\delta }'\left( t-{{t}_{0}} \right)$$ 

I got the same question. And this is the demo markdown

**Comment by wufeng87** [comment] 2019-08-29 05:02
My editor support use `$$ $$` to right katex, however marked.js does not recognize it.

**Comment by wufeng87** [comment] 2019-08-29 05:05
And these code run good with latest marked.js:
a$$sin(\Omega_{0}n)$$,b$$e^{j\Omega_{0}n}$$ $$\Omega_{0}$$c$$2\pi$$

**Comment by wufeng87** [comment] 2019-08-29 05:09
> Anything that is code should be wrapped in backticks (`` ` ``), or indented 4 spaces. Code won't be rendered as markdown.
> 

@UziTech  You are right, thanks.

**Comment by wufeng87** [comment] 2019-08-29 05:18
And I wonder if I could change the `InlineLexer.prototype.output` method to check em when text not in `$$ $$` ? Thanks

**Comment by wufeng87** [comment] 2019-08-29 05:50
I thought I could custom this:
```
Renderer.prototype.em = function(text) {
  return '<em>' + text + '</em>';
};

```

To check text if contains `$$`

**Comment by UziTech** [comment] 2019-08-29 13:39
If you want to use katex with marked you can modify the renderer to check if code spans are katex.

I pulled this out of [marked-katex](https://github.com/linxiaowu66/marked-kaTex) (it hasn't been updated in a while so I wouldn't use that package);

Here is a working example:

```js
const marked = require("marked");
const katex = require("katex");

const renderer = new marked.Renderer();

mathsExpression = function(expr) {
  if (expr.match(/^\$\$.*\$\$$/s)) {
  	expr = expr.substr(2, expr.length - 4);
  	return katex.renderToString(expr, {displayMode: true});
  } else if (expr.match(/^\$.*\$$/s)) {
    expr = expr.substr(1, expr.length - 2);
    return katex.renderToString(expr, {displayMode: false});
  }
}

const rendererCode = renderer.code;
renderer.code = function (code, lang, escaped) {
  if (!lang) {
    const math = mathsExpression(code);
    if (math) {
      return math;
    }
  }

  return rendererCode(code, lang, escaped);
}

const rendererCodespan = renderer.codespan;
renderer.codespan = function (text) {
  const math = mathsExpression(text);

  if (math) {
    return math;
  }

  return rendererCodespan(text);
}



const md = "`$$c=\sqrt{a^2 + b^2}$$`"

console.log(marked(md, {renderer}));

```

**Comment by wufeng87** [comment] 2019-09-05 02:44
Could I add some code or config to make the `$$ $$` part not be marked? Thanks.

**Comment by sandy-shi** [comment] 2019-09-05 09:38
> (`` ` ``)
Firstly, use (`) can solve the problem.
some markdown that isn't working correctly
`${x}_{2}$,${x}_{2}$`
this code has two '_',marked cant render it correctly, render the '_' to <em>,
but this code`$x_2$,$x_2$`,marked render it successfully, do not render '_' to <em>

**Comment by sandy-shi** [comment] 2019-09-05 09:48
> Anything that is code should be wrapped in backticks (`` ` ``), or indented 4 spaces. Code won't be rendered as markdown.
> 
> Could you share some markdown that isn't working correctly?


Firstly, **use (`` ` ``)can solve the problem**. 

some markdown that isn't working correctly
1.` ${x}_{2}$,${x}_{2}$`,
this code has two '\_', marked cant render it correctly, render the '\_' to \<em\>, 

2.`$x_2$,$x_2$`,or `${x}_2$,${x}_2$`
but this code, marked render it successfully, do not render '\_' to \<em\>

**Comment by sandy-shi** [comment] 2019-09-05 09:49
> If you want to use katex with marked you can modify the renderer to check if code spans are katex.
> 
> I pulled this out of [marked-katex](https://github.com/linxiaowu66/marked-kaTex) (it hasn't been updated in a while so I wouldn't use that package).
> 
> Here is a working example:
> 
> ```js
> const marked = require('marked');
> const katex = require('katex');
> 
> const renderer = new marked.Renderer();
> 
> function mathsExpression(expr) {
>   if (expr.match(/^\$\$[\s\S]*\$\$$/)) {
>     expr = expr.substr(2, expr.length - 4);
>     return katex.renderToString(expr, { displayMode: true });
>   } else if (expr.match(/^\$[\s\S]*\$$/)) {
>     expr = expr.substr(1, expr.length - 2);
>     return katex.renderToString(expr, { isplayMode: false });
>   }
> }
> 
> const rendererCode = renderer.code;
> renderer.code = function(code, lang, escaped) {
>   if (!lang) {
>     const math = mathsExpression(code);
>     if (math) {
>       return math;
>     }
>   }
> 
>   return rendererCode(code, lang, escaped);
> };
> 
> const rendererCodespan = renderer.codespan;
> renderer.codespan = function(text) {
>   const math = mathsExpression(text);
> 
>   if (math) {
>     return math;
>   }
> 
>   return rendererCodespan(text);
> };
> 
> const md = '`$$c=\sqrt{a^2 + b^2}$$`';
> 
> console.log(marked(md, { renderer: renderer }));
> ```



> Anything that is code should be wrapped in backticks (`` ` ``), or indented 4 spaces. Code won't be rendered as markdown.
> 
> Could you share some markdown that isn't working correctly?

@UziTech

**Comment by sandy-shi** [comment] 2019-09-05 09:50
> Anything that is code should be wrapped in backticks (`` ` ``), or indented 4 spaces. Code won't be rendered as markdown.
> 
> Could you share some markdown that isn't working correctly?

@UziTech

**Comment by wufeng87** [comment] 2019-09-05 12:11
```
console.log(marked('$$(\lambda_{1})^{n}u(n)*(\lambda_{2})^{n}u(n)$$', { renderer: renderer }));
VM423:1 <p>$$(lambda<em>{1})^{n}u(n)*(lambda</em>{2})^{n}u(n)$$</p>
```

**Comment by UziTech** [comment] 2019-09-05 12:23
I'm going to close this because it sounds like using backticks solved your problem. If that is not the case, feel free to reopen it.

**Closed by UziTech** 2019-09-05 12:23 UTC
Labels: question

**Comment by alexeypetrushin** [comment] 2020-01-17 22:38
@UziTech thanks for the example. Is it possible to modify the example code so it would work even if the math code is not wrapped with ticks? So, this would also work `'some text $$c=\sqrt{a^2 + b^2}$$ another text'`?

**Comment by alexeypetrushin** [comment] 2020-01-17 23:51
If anyone needs it - another example, KaTeX rendered everywhere except of inside the code ticks.

```typescript
type something = any

const marked = require('marked')
const katex = require('katex')

const renderer = new marked.Renderer()

let i = 0
const next_id = () => `__special_katext_id_${i++}__`
const math_expressions: { [key: string]: { type: 'block' | 'inline', expression: string } } = {}

function replace_math_with_ids(text: string) {
  // Qllowing newlines inside of `$$...$$`
  text = text.replace(/\$\$([\s\S]+?)\$\$/g, (_match, expression) => {
    const id = next_id()
    math_expressions[id] = { type: 'block', expression }
    return id
  })

  // Not allowing newlines inside of `$...$`
  text = text.replace(/\$([^\n]+?)\$/g, (_match, expression) => {
    const id = next_id()
    math_expressions[id] = { type: 'inline', expression }
    return id
  })

  return text
}

const original_listitem = renderer.listitem
renderer.listitem = function(text: string, task: boolean, checked: boolean) {
  return original_listitem(replace_math_with_ids(text), task, checked)
}

const original_paragraph = renderer.paragraph
renderer.paragraph = function(text: string) {
  return original_paragraph(replace_math_with_ids(text))
}

const original_tablecell = renderer.tablecell
renderer.tablecell = function(content: string, flags: Object) {
  return original_tablecell(replace_math_with_ids(content), flags)
}

// Inline level, maybe unneded
const original_text = renderer.text
renderer.text = function(text: string) {
  return original_text(replace_math_with_ids(text))
}


// const md = 'some text `$$c=\sqrt{a^2 + b^2}$$` another text'
const md = 'some text $$c=\sqrt{a^2 + b^2}$$ another text'

const rendered_md_only: string = marked(md, { renderer: renderer })
console.log(rendered_md_only)

const rendered = rendered_md_only.replace(/(__special_katext_id_\d+__)/g, (_match, capture) => {
  const { type, expression } = math_expressions[capture]
  return katex.renderToString(expression, { displayMode: type == 'block' })
})
console.log(rendered)
```

**Comment by agustingabiola** [comment] 2020-10-04 16:49
> If you want to use katex with marked you can modify the renderer to check if code spans are katex.
> 
> I pulled this out of [marked-katex](https://github.com/linxiaowu66/marked-kaTex) (it hasn't been updated in a while so I wouldn't use that package).
> 
> Here is a working example:
> 
> ```js
> const marked = require('marked');
> const katex = require('katex');
> 
> const renderer = new marked.Renderer();
> 
> function mathsExpression(expr) {
>   if (expr.match(/^\$\$[\s\S]*\$\$$/)) {
>     expr = expr.substr(2, expr.length - 4);
>     return katex.renderToString(expr, { displayMode: true });
>   } else if (expr.match(/^\$[\s\S]*\$$/)) {
>     expr = expr.substr(1, expr.length - 2);
>     return katex.renderToString(expr, { isplayMode: false });
>   }
> }
> 
> const rendererCode = renderer.code;
> renderer.code = function(code, lang, escaped) {
>   if (!lang) {
>     const math = mathsExpression(code);
>     if (math) {
>       return math;
>     }
>   }
> 
>   return rendererCode(code, lang, escaped);
> };
> 
> const rendererCodespan = renderer.codespan;
> renderer.codespan = function(text) {
>   const math = mathsExpression(text);
> 
>   if (math) {
>     return math;
>   }
> 
>   return rendererCodespan(text);
> };
> 
> const md = '`$$c=\sqrt{a^2 + b^2}$$`';
> 
> console.log(marked(md, { renderer: renderer }));
> ```

`renderer.codespan` doing like this you are actually changing the reference. You will need to create a new renderer and reference that inside the one you are changing:

```javascript
const unchanged = new Renderer()
const myRenderer = new Renderer()

myRenderer.codespan = (params) => {
  ...
  return unchanged.codespan(params)
}
```

**Comment by usstq** [comment] 2021-07-23 03:09
> > If you want to use katex with marked you can modify the renderer to check if code spans are katex.
> > I pulled this out of [marked-katex](https://github.com/linxiaowu66/marked-kaTex) (it hasn't been updated in a while so I wouldn't use that package).
> > Here is a working example:
> > ```js
> > const marked = require('marked');
> > const katex = require('katex');
> > 
> > const renderer = new marked.Renderer();
> > 
> > function mathsExpression(expr) {
> >   if (expr.match(/^\$\$[\s\S]*\$\$$/)) {
> >     expr = expr.substr(2, expr.length - 4);
> >     return katex.renderToString(expr, { displayMode: true });
> >   } else if (expr.match(/^\$[\s\S]*\$$/)) {
> >     expr = expr.substr(1, expr.length - 2);
> >     return katex.renderToString(expr, { isplayMode: false });
> >   }
> > }
> > 
> > const rendererCode = renderer.code;
> > renderer.code = function(code, lang, escaped) {
> >   if (!lang) {
> >     const math = mathsExpression(code);
> >     if (math) {
> >       return math;
> >     }
> >   }
> > 
> >   return rendererCode(code, lang, escaped);
> > };
> > 
> > const rendererCodespan = renderer.codespan;
> > renderer.codespan = function(text) {
> >   const math = mathsExpression(text);
> > 
> >   if (math) {
> >     return math;
> >   }
> > 
> >   return rendererCodespan(text);
> > };
> > 
> > const md = '`$$c=\sqrt{a^2 + b^2}$$`';
> > 
> > console.log(marked(md, { renderer: renderer }));
> > ```
> 
> `renderer.codespan` doing like this you are actually changing the reference. You will need to create a new renderer and reference that inside the one you are changing:
> 
> ```js
> const unchanged = new Renderer()
> const myRenderer = new Renderer()
> 
> myRenderer.codespan = (params) => {
>   ...
>   return unchanged.codespan(params)
> }
> ```
Not exactly right about the root cause, the rendererCodespan member function is still there and not changed by assignment to renderer.codespan. it's just that your way of calling it:

```JS
   ...
   return rendererCodespan(text);
```

it's a normal function, to call it like member function you need:

```JS
   ...
   return rendererCodespan.call(this, text);
```

**Comment by qwqcode** [comment] 2022-04-19 11:18
> If anyone needs it - another example, KaTeX rendered everywhere except of inside the code ticks.
> 
> ```ts
> type something = any
> 
> const marked = require('marked')
> const katex = require('katex')
> 
> const renderer = new marked.Renderer()
> 
> let i = 0
> const next_id = () => `__special_katext_id_${i++}__`
> const math_expressions: { [key: string]: { type: 'block' | 'inline', expression: string } } = {}
> 
> function replace_math_with_ids(text: string) {
>   // Qllowing newlines inside of `$$...$$`
>   text = text.replace(/\$\$([\s\S]+?)\$\$/g, (_match, expression) => {
>     const id = next_id()
>     math_expressions[id] = { type: 'block', expression }
>     return id
>   })
> 
>   // Not allowing newlines or space inside of `$...$`
>   text = text.replace(/\$([^\n\s]+?)\$/g, (_match, expression) => {
>     const id = next_id()
>     math_expressions[id] = { type: 'inline', expression }
>     return id
>   })
> 
>   return text
> }
> 
> const original_listitem = renderer.listitem
> renderer.listitem = function(text: string, task: boolean, checked: boolean) {
>   return original_listitem(replace_math_with_ids(text), task, checked)
> }
> 
> const original_paragraph = renderer.paragraph
> renderer.paragraph = function(text: string) {
>   return original_paragraph(replace_math_with_ids(text))
> }
> 
> const original_tablecell = renderer.tablecell
> renderer.tablecell = function(content: string, flags: Object) {
>   return original_tablecell(replace_math_with_ids(content), flags)
> }
> 
> // Inline level, maybe unneded
> const original_text = renderer.text
> renderer.text = function(text: string) {
>   return original_text(replace_math_with_ids(text))
> }
> 
> 
> // const md = 'some text `$$c=\sqrt{a^2 + b^2}$$` another text'
> const md = 'some text $$c=\sqrt{a^2 + b^2}$$ another text'
> 
> const rendered_md_only: string = marked(md, { renderer: renderer })
> console.log(rendered_md_only)
> 
> const rendered = rendered_md_only.replace(/(__special_katext_id_\d+__)/g, (_match, capture) => {
>   const { type, expression } = math_expressions[capture]
>   return katex.renderToString(expression, { displayMode: type == 'block' })
> })
> console.log(rendered)
> ```

In cases of white spaces in a latex expresion, the no-newlines regex `/\$([^\n\s]+?)\$/g` may be wrong, it should be `/\$([^\n]+?)\$/g`

not match:

![image](https://user-images.githubusercontent.com/22412567/163992118-46006b1f-b9e4-46a7-a7ee-22e7fce3d86e.png)

it works:

![image](https://user-images.githubusercontent.com/22412567/163992174-e907b893-e6bd-47dd-a71e-0d9badab04ae.png)

**Comment by rockie-yang** [comment] 2022-07-23 19:43
Here is another one based @qwqcode 's solution.

    import marked from "marked";
    import katex from "katex";
    import "katex/dist/katex.css";
    
    const renderer = new marked.Renderer();
    
    const replacer = (((blockRegex, inlineRegex) => (text) => {
        text = text.replace(blockRegex, (match, expression) => {
            return katex.renderToString(expression, {displayMode: true});
        });
    
        text = text.replace(inlineRegex, (match, expression) => {
            return katex.renderToString(expression, {displayMode: false});
        });
    
        return text;
    })(/\$\$([\s\S]+?)\$\$/g, /\$([^\n\s]+?)\$/g));
    
    const replaceTypes = ["listitems", "paragraph", "tablecell", "text"];
    replaceTypes.forEach(type => {
        const original = renderer[type];
        renderer[type] = (...args) => {
            args[0] = replacer(args[0]);
            return original(...args);
        };
    });
    
    export default (md) => {
        return marked(md, {renderer: renderer});
    }

**Comment by DDKK64** [comment] 2024-04-23 07:22
If anyone is trying to manually render Markdown and Latex formulae into HTML, rendering LaTex before markdown works for me.

The following example uses MathJax. But I assume KaTex will work in similar way:

```js
fetch("articles/calculus.md")
  .then((res) => res.text())
  .then((text) => {
      // Dynamicly load the content. This is unnecessary if you use static content.
      document.getElementById('article').innerHTML = text;
      // Render LaTex
      return MathJax.typesetPromise()
  }).then(() => {
      // Then render Markdown
      text = document.getElementById('article').innerHTML;
      document.getElementById('article').innerHTML = marked.parse(text);
  }
```
