### ISSUE TITLE
Marked doesn't output italics tags correctly when asterisks are outside double quoted strings

### ISSUE THREAD

**Issue by ctessmer** [markedjs/marked#1473] opened 2019-04-16 20:26 UTC
**Describe the bug**
Marked doesn't output `<em>` tags correctly when asterisks are outside double quoted strings.

**To Reproduce**
Steps to reproduce the behavior from CLI:

Input: `$ marked -s '*"I like turtles."*'`
Errant output: `<p>*&quot;I like turtles.&quot;*</p>`

**Expected behavior**
Expected output: `<p><em>&quot;I like turtles.&quot;</em></p>`

**A slight workaround**
Pay particular attention to the inverting of the asterisk/quotes here (this leads to non-italicized quotes, but oh well):

Input: $ `marked -s '"*I like turtles.*"'`
Output: `<p>&quot;<em>I like turtles.</em>&quot;</p>`

**Comment by UziTech** [comment] 2019-04-17 04:03
duplicate of #1358

**Closed by UziTech** 2019-04-17 04:03 UTC
