### ISSUE TITLE
Provide type definition in .d.ts file

### ISSUE THREAD

**Issue by jingkaimori** [markedjs/marked#2662] opened 2022-11-23 11:24 UTC
**Describe the feature**
Provide a type definition file, like [index.d.ts](https://cdn.jsdelivr.net/npm/@types/marked@4.0.7/) in version 4.0.7.

**Why is this feature necessary?**
Without type definition, it's impossible to know whether a token contains some field. 

**Describe alternatives you've considered**
Export those jsdoc comment along with lib file.

**Comment by UziTech** [comment] 2022-11-23 13:53
Duplicate of #1732

**Closed by UziTech** 2022-11-23 13:53 UTC
