### ISSUE TITLE
Inserted <p> into <li> on different unordered lists

### ISSUE THREAD

**Issue by ybiquitous** [markedjs/marked#1461] opened 2019-04-08 01:26 UTC
**Describe the bug**

When putting different two unordered lists (`-` and `*`) with blank lines, a `<p>` tag is inserted into `<li>` tag.

E.g.
```md
- a1
- a2

* b1
* b2
```

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?outputType=html&text=-%20a1%0A-%20a2%0A%0A*%20b1%0A*%20b2%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.6.2)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=-%20a1%0A-%20a2%0A%0A*%20b1%0A*%20b2%0A%0A)

On terminal:

1. Install marked: `npm install --save marked@0.6.2`
2. Run marked:
```
$ cat <<EOF | ./node_modules/.bin/marked
- a1
- a2

* b1
* b2
EOF
```
3. Actual output (or error) is:
```
<ul>
<li><p>a1</p>
</li>
<li><p>a2</p>
</li>
<li><p>b1</p>
</li>
<li><p>b2</p>
</li>
</ul>
```

**Expected behavior**

Like CommonMark, I think marked should output the following HTML:
```
<ul>
<li>a1</li>
<li>a2</li>
</ul>
<ul>
<li>b1</li>
<li>b2</li>
</ul>
```

**Comment by UziTech** [comment] 2019-04-08 14:50
Adding an extra new line will make it render correctly but this is a bug.

**Comment by ybiquitous** [comment] 2019-04-09 01:33
I think so, too. 👍

**Comment by ansuz** [comment] 2019-06-05 13:41
I played around with the parser and saw [a suspicious looking line](https://github.com/markedjs/marked/blob/master/lib/marked.js#L22).

The patch below seems to fix this issue:

```diff
22c22
<   list: /^( *)(bull) [\s\S]+?(?:hr|def|\n{1,}(?! )(?!\1bull )\n*|\s*$)/,
---
>   list: /^( *)(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,
```
...but I don't know that it doesn't cause other problems which are potentially much worse.

If anyone can point me towards any tests I should run I can turn this into a PR pretty quickly.

**Comment by UziTech** [comment] 2019-06-05 13:49
Running `npm test` from your marked directory will run the tests.

Alternatively, if you submit a PR the tests will automatically run on travis-ci

**Comment by ansuz** [comment] 2019-06-05 14:09
As my PR says, the fix causes all sorts of failures. If the PR isn't acceptable hopefully it at least serves as a good starting point for an investigation into the problem.

**Comment by UziTech** [comment] 2019-06-05 15:12
I don't think that is the right fix. It seems like the right fix should change the regex to distinguish between `-` and `*`

**Comment by ansuz** [comment] 2019-06-11 08:54
@UziTech: as per your comment on my PR:

> according to [the original markdown spec](https://daringfireball.net/projects/markdown/syntax#list):
> 
> > If list items are separated by blank lines, Markdown will wrap the items in `<p>` tags in the HTML output.

This seems to be intended behaviour, which I guess invalidates your above comment:

> Adding an extra new line will make it render correctly but this is a bug.

If that's the case, I suppose this issue should be marked as _wontfix_ and closed?

**Comment by UziTech** [comment] 2019-06-11 13:52
The original issue uses two different list item styles (`-` and `*`) which should render as two separate lists with a single blank line between them. Your test only uses a single list item style (`*`) which, as my comment states, should render a single loose list.

**Closed** 2020-11-04 21:23 UTC
Labels: L2 - annoying, category: lists

**Comment by yannicklescure** [comment] 2022-05-14 18:56
Hi, I'm using version "4.0.15". The bug is still present (or is back).

**Comment by calculuschild** [comment] 2022-05-14 19:29
@yannicklescure Can you give us an example input and output? We can add it to our test suite and reopen this issue.

**Comment by yannicklescure** [comment] 2022-05-14 21:36
@calculuschild I did further test trying to narrow the issue. Here is what I have tried.
```
- a1
- a2

* b1
* b2

1. c1
2. c2

* d1

* d2

* f1

* f2

1. e1

2. e2
```

The serie a, b, c gives the expected result i.e.: <li>a1</li>.
The serie d, e, f gives the list of elements adding p inside li i.e.: <li><p>a1</p></li>. Notice the added space between the lines.

**Comment by UziTech** [comment] 2022-05-15 02:54
That is called a [loose list](https://spec.commonmark.org/0.30/#loose) and that is intended behavior that follows the CommonMark spec.
