### ISSUE TITLE
Leaving Tabs in Fenced Code

### ISSUE THREAD

**Issue by manngo** [markedjs/marked#2156] opened 2021-08-01 04:47 UTC
**Describe the feature**
There may already be way of doing this, but I can’t find it.
Is it possible to get Marked _not_ to replace tabs with spaces in fenced code?

**Why is this feature necessary?**
I use Marked in an Electron application to render markdown, and it does a brilliant job. However, I have no control over this feature, as far as I am aware.
Personally I prefer tabs, though I know some others don’t. For me, however, it makes copying code easier and formatting output easier if I can have the tabs.

**Describe alternatives you've considered**
I can undo the spaces using something like `replace(/    /g,'\t');`, but (a) that’s not 100% reliable, and (b) I think it would make more sense not to have to reverse a feature.
If the solution lies in a custom render function, I’m happy with that.

**Comment by UziTech** [comment] 2021-08-01 14:55
Duplicate of #1668

There is no way of doing this currently. If you would like to submit a PR to fix it that would be much appreciated. 😁👍

**Closed by UziTech** 2021-08-01 14:55 UTC
