### ISSUE TITLE
Content between list item is wrapped inside item.

### ISSUE THREAD

**Issue by 07akioni** [markedjs/marked#1750] opened 2020-08-19 14:54 UTC
**Describe the bug**
```md
- 1
# 2
- 3
```
will generate
```html
<ul>
<li>1<h1 id="2">2</h1>
</li>
<li>3</li>
</ul>
```
**To Reproduce**
1. [Marked Demo](https://marked.js.org/demo/?outputType=html&text=-%201%0A%23%202%0A-%203&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.1.1)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=-%201%0A%23%202%0A-%203)

It seems to be a very old bug since version `0.7.0`.

**Expected behavior**

```html
<ul>
<li>1</li>
<h1 id="2">2</h1>
<li>3</li>
</ul>
```

**Comment by UziTech** [comment] 2020-08-19 15:13
duplicate of #1047 

The work around is to put a new line after the list. [demo](https://marked.js.org/demo/?text=-%201%0A%0A%23%202%0A-%203&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.1.1)

**Closed by UziTech** 2020-08-19 15:13 UTC
