### ISSUE TITLE
SyntaxError: invalid identity escape in regular expression

### ISSUE THREAD

**Issue by MajedMuhammad** [markedjs/marked#2816] opened 2023-05-25 06:13 UTC
**Marked version: 4.3.0**

Everything works fine, but when running in Firefox 71, shows this error "SyntaxError: invalid identity escape in regular expression".

**To Reproduce**
Steps to reproduce the behavior: Just import `marked` and run the app using Firefox 71. 

**Expected behavior**
It should support legacy browsers.

**Current behavior** 
It fails with legacy browsers such as Firefox 71.

**Comment by UziTech** [comment] 2023-05-25 12:57
Duplicate of #2339

**Closed by UziTech** 2023-05-25 12:57 UTC
