### ISSUE TITLE
[Blockquotes]: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ishen7** [markedjs/marked#1501] opened 2019-06-12 08:47 UTC
**Describe the bug**

Nested references do not work and are inconsistent with the performance of commonmark

**To Reproduce**

[Marked Demo](https://marked.js.org/demo/?text=%23%23%20It%20works%0A%0A%3E%20123%0A%0A%3E%3E%20123%0A%0A%3E%3E%3E%20123%0A%0A%0A%0A%23%23%20It%20not%20works%0A%0A%23%23%23%20example%201%0A%0A-%20ErrorCode%3A%0A%0A%20%20%60%60%60%0A%20%20%23%23%20one%0A%0A%20%20%3E%20123%0A%20%20%3E%3E%3E%20123%0A%0A%20%20%23%23%20two%0A%0A%20%20%3E%20123%0A%20%20%3E%3E%20123%0A%20%20%3E%3E%3E%20123%0A%0A%20%20%23%23%20three%0A%0A%20%20%3E%0A%20%20%3E%3E%20123%0A%20%20%3E%3E%3E%20123%0A%0A%20%20%23%23%20four%0A%0A%20%20%3E%0A%20%20%3E%3E%20123%0A%20%20%3E%3E%20123%0A%20%20%60%60%60%0A%0A%0A-%20ErrorInfo%3A%0A%0A%20%20Uncaught%20TypeError%3A%20Cannot%20read%20property%20%27type%27%20of%20undefined%0A%0A%23%23%23%20example%202%0A%0A-%20ErrorCode%3A%0A%0A%20%20%60%60%60%0A%20%20%3E%0A%0A%20%20%3E%3E%20123%0A%20%20%3E%3E%20123%0A%20%20%60%60%60%0A%0A%0A-%20ErrorInfo%3A%0A%0A%20%20no%20newline&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

[CommonMark Demo](https://spec.commonmark.org/dingus/?text=%23%23%20It%20works%0A%0A>%20123%0A%0A>>%20123%0A%0A>>>%20123%0A%0A%0A%0A%23%23%20It%20not%20works%0A%0A%23%23%23%20example%201%0A%0A-%20ErrorCode%3A%0A%0A%20%20%60%60%60%0A%20%20%23%23%20one%0A%0A%20%20>%20123%0A%20%20>>>%20123%0A%0A%20%20%23%23%20two%0A%0A%20%20>%20123%0A%20%20>>%20123%0A%20%20>>>%20123%0A%0A%20%20%23%23%20three%0A%0A%20%20>%0A%20%20>>%20123%0A%20%20>>>%20123%0A%0A%20%20%23%23%20four%0A%0A%20%20>%0A%20%20>>%20123%0A%20%20>>%20123%0A%20%20%60%60%60%0A%0A%0A-%20ErrorInfo%3A%0A%0A%20%20Uncaught%20TypeError%3A%20Cannot%20read%20property%20%27type%27%20of%20undefined%0A%0A%23%23%23%20example%202%0A%0A-%20ErrorCode%3A%0A%0A%20%20%60%60%60%0A%20%20>%0A%0A%20%20>>%20123%0A%20%20>>%20123%0A%20%20%60%60%60%0A%0A%0A-%20ErrorInfo%3A%0A%0A%20%20no%20newline)

**Expected behavior**

Can work without a line break, and the same level of nesting should be a separate line, see the example below.

  ## one

  > 123
  >>> 123

  ## two

  > 123
  >> 123
  >>> 123

  ## three

  >
  >> 123
  >>> 123

  ## four

  >
  >> 123
  >> 123

**Comment by UziTech** [comment] 2019-06-12 13:34
Duplicate of #1494

**Closed by UziTech** 2019-06-12 13:34 UTC
