### ISSUE TITLE
Marked.js incorrectly renders table with inline code block containing pipes (|)

### ISSUE THREAD

**Issue by N0rbert** [markedjs/marked#1953] opened 2021-02-23 15:24 UTC
**Marked version:**

latest master as on https://marked.js.org/demo .

**Describe the bug**

I have table with inline code in cell and pipes. I edit it using MarkText (see  <https://github.com/marktext/marktext/issues/660#issuecomment-784276369>). 

**To Reproduce**

Use code fragment shown below:

```
| **Command**                                                            | **Done?** |
|:-----------------------------------------------------------------------|:---------:|
| `sudo apt purge $(dpkg -l | grep ^ii | grep grub | awk '{print $2}')`  | v         |
```

**Expected behavior**

Should be correctly rendered as shown below by ReText:

![retext](https://user-images.githubusercontent.com/309456/108865450-500e6700-7604-11eb-9c08-8484426636e0.png)

**Comment by UziTech** [comment] 2021-02-23 15:44
This follows GFM. `|` need to be escaped inside tables like `\|` even inside code blocks.

duplicate of #1777

**Closed by UziTech** 2021-02-23 15:44 UTC
