### ISSUE TITLE
const prevRenderer = extensions.renderers?.[ext.name];

### ISSUE THREAD

**Issue by Bielykh-Artem** [markedjs/marked#2110] opened 2021-06-16 09:37 UTC
const prevRenderer = extensions.renderers?.[ext.name];
SyntaxError: Unexpected token '.'

**Comment by Bulkman** [comment] 2021-06-16 09:55
Package semantic-release broke cuz of this. They are having "marked": "^2.0.0" in package.json.
Requesting update as soon as possible

**Comment by Bulkman** [comment] 2021-06-16 09:57
> Package semantic-release broke cuz of this. They are having "marked": "^2.0.0" in package.json.
> Requesting update as soon as possible

Though more reasonable would be requesting update in semantic-release doc to drop Node < 14

**Comment by Aggtaa** [comment] 2021-06-16 11:49
protobufjs via jsdoc broke because of this

**Comment by UziTech** [comment] 2021-06-16 13:55
Duplicate of #2106

**Closed by UziTech** 2021-06-16 13:55 UTC
