### ISSUE TITLE
Creates invalid HTML

### ISSUE THREAD

**Issue by Sorunome** [markedjs/marked#1277] opened 2018-05-26 17:21 UTC
**Describe the bug**
```
marked('<h2>foo bar</h2><pre>foo\n\nbar\n</pre>')
"<h2>foo bar</h2><pre>foo

<p>bar
</pre></p>
"

        
```

**Expected behavior**
return this:
```
"<h2>foo bar</h2><pre>foo

bar
</pre>
"
```

**Comment by UziTech** [comment] 2018-05-27 22:30
What version of marked are you using.

It seems to be working correctly in the [demo](https://marked.js.org/demo/?outputType=html&text=%3Ch2%3Efoo%20bar%3C%2Fh2%3E%3Cpre%3Efoo%5Cn%5Cnbar%5Cn%3C%2Fpre%3E)

**Comment by styfle** [comment] 2018-05-28 16:40
@Sorunome GitHub is not a good place to grab code since the code is always changing and might break.

Try the latest release v0.4.0 and see if that works for you: https://cdn.jsdelivr.net/npm/marked@0.4.0/marked.min.js

**Comment by Sorunome** [comment] 2018-05-28 17:21
Nope, still doesn't work for me. I didn't think may be related, but yeah i'm also using this:

```
		var markedRenderer = new marked.Renderer();
		markedRenderer.code = function(code, lang) {
			return '<pre>'+code+'</pre>';
		};
		markedRenderer.heading = function(text, level, raw) {
			level++; // we don't allow h1, so we actually do h2....whatever
			return '<h' + level + '>' + text + '</h' + level + '>\n';
		};
		marked.setOptions({
			renderer: markedRenderer,
			headerIds: false,
		});
```

**Comment by styfle** [comment] 2018-05-30 21:08
I tried from the command line and was able to reproduce.

```js
var str = '<h2>foo bar</h2><pre>foo\n\nbar\n</pre>';
marked(str);
/*
"<h2>foo bar</h2><pre>foo

<p>bar
</pre></p>
"
*/
```

The `p` tag is wrapping the `pre` for some strange reason.

**Comment by RomanGotsiy** [comment] 2018-10-03 10:05
This is actually valid output according to the CommonMark spec:

Your first line is parsed as an HTML block (see Condition # 6 in the [spec](https://spec.commonmark.org/0.28/#html-blocks)). The end condition for it is:

> line is followed by a blank line.

which is exacly what we have here. Thus the following text `bar\n</pre>` is treated as a paragraph and is wrapped in `p` tag

Commonmark playground:
https://spec.commonmark.org/dingus/?text=%3Ca%20%20%2F%3E%3Cb2%0Adata%3D%22foo%22%20%3E%0A

**Comment by styfle** [comment] 2018-10-03 13:09
@RomanGotsiy You're right, this is exactly the same output as commonmark 👍 

https://spec.commonmark.org/dingus/?text=%3Ch2%3Efoo%20bar%3C%2Fh2%3E%3Cpre%3Efoo%0A%0Abar%0A%3C%2Fpre%3E

https://marked.js.org/demo/?outputType=html&text=%3Ch2%3Efoo%20bar%3C%2Fh2%3E%3Cpre%3Efoo%0A%0Abar%0A%3C%2Fpre%3E

Closing.

**Closed by styfle** 2018-10-03 13:09 UTC
