### ISSUE TITLE
Checklists are rendered with a dot

### ISSUE THREAD

**Issue by andoks** [markedjs/marked#1701] opened 2020-06-08 11:47 UTC
**Description**
Marked renders checkboxes in checlists with a dot before the checkbox.

**To Reproduce**
Create checklist using the `- [ ] item 1` syntax, observe that the dot is rendered

1. [Marked Demo](https://marked.js.org/demo/?text=**To-dos**%0A%0A-%20%5B%20%5D%20Test%20hyphen%0A-%20%5Bx%5D%20Test%20hyphen%20(2)%0A%0A%0A*%20%5B%20%5D%20Test%20asterisk%0A*%20%5BX%5D%20Test%20asterisk%20(2)%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.1.0)
2. CommonMark demo not possible since this is GFM markdown
3. Similar issue with atom https://github.com/atom/markdown-preview/issues/166
4. [Githubs' documentation for tasklists](https://help.github.com/en/github/managing-your-work-on-github/about-task-lists), checkboxes are rendered without list-dot

**Expected behavior**
Dot is not rendered, checkbox is the item symbol

**Comment by UziTech** [comment] 2020-06-08 13:48
duplicate of #1667 

marked just outputs the html. css styling is the responsibility of the user.

**Closed by UziTech** 2020-06-08 13:48 UTC
