### ISSUE TITLE
em and strong (***〜***)

### ISSUE THREAD

**Issue by plotpoi** [markedjs/marked#1860] opened 2020-12-04 07:45 UTC
Thanks for the great project.

When em and strong are used together, there appears to be a difference in the analysis results.
At the beginning of a line, em and strong are parsed properly, but in a sentence, they are not.
Is this as expected? We would be happy to confirm it when you have time.

The following link is for your reference.

https://marked.js.org/demo/?text=AAAAAAAA***AA***AAAA%0A%0A***AA***AAAAAAAAAAAA%0A%0A***AA***AAAAAA***AAA***AAA%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

**Comment by calculuschild** [comment] 2020-12-04 17:21
Looks like this is covered by [GFM Example 425](https://github.github.com/gfm/#example-425) which isn't in our test specs. It looks like the GFM spec has been updated somewhat since the original test cases were made (many of the example numbers no longer match). Do we also want to update those tests now to help avoid more regressions like this?

**Comment by UziTech** [comment] 2020-12-04 17:33
@calculuschild this is covered by CommonMark [example 415](https://spec.commonmark.org/0.29/#example-415)

It was marked as `shouldFail` because v1.1.0 had `strong` and `em` tags switched so it technically wasn't passing in v1.1.0 but the result in the browser was the same.

**Comment by calculuschild** [comment] 2020-12-04 22:01
Alright. I'm looking into this.

**Comment by calculuschild** [comment] 2020-12-06 09:09
Got a working solution. Just need to clean up the messy code.

**Closed** 2021-02-07 22:25 UTC
Labels: L1 - broken, category: inline elements
