### ISSUE TITLE
Add async API

### ISSUE THREAD

**Issue by vixalien** [markedjs/marked#2519] opened 2022-07-04 01:22 UTC
**What pain point are you perceiving?.**
It's a bad thing that marked still uses callbacks. using the new async/await features of javascript might be a good thing.

**Describe the solution you'd like**
Usage of async/await instead of callbacks. Would be useful for plugins as well ass rendering.

**Comment by UziTech** [comment] 2022-07-04 01:28
Duplicate of #458

**Closed by UziTech** 2022-07-04 01:28 UTC
