### ISSUE TITLE
Escaping character '*' inside of an italic text doesn't take it well

### ISSUE THREAD

**Issue by rtxa** [markedjs/marked#1485] opened 2019-05-04 14:20 UTC
**Describe the bug**
When you are escaping the character * inside of an italic text (using *), makes it work bad. I found a workaround for this issue by turning on the pedantic option.

**To Reproduce**
* Pedantic OFF
  [Marked Demo](https://marked.js.org/demo/?text=%23%23%20Installation%0AOpen%20*zx%5C_plugin%5C_%5C**%2C%20and%20**extract**%20the%20content%20inside%20*valve*%20folders&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
* Pedantic ON (workaround)
  [Marked Demo](https://marked.js.org/demo/?text=%23%23%20Installation%0AOpen%20*zx%5C_plugin%5C_%5C**%2C%20and%20**extract**%20the%20content%20inside%20*valve*%20folders&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20true%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**
The text should look like this:
* [CommonMark Demo](https://spec.commonmark.org/dingus/?text=%23%23%20Installation%0AOpen%20*zx%5C_plugin%5C_%5C**%2C%20and%20**extract**%20the%20content%20inside%20*valve*%20folders)

I don't know if this is expected, but this isn't happening in CommonMark, so I think this is an issue.

**Comment by UziTech** [comment] 2019-05-04 22:43
Duplicate of #520

**Closed by UziTech** 2019-05-04 22:43 UTC
