### ISSUE TITLE
How to turn on CommonMark 

### ISSUE THREAD

**Issue by daggett206** [markedjs/marked#1264] opened 2018-05-11 11:07 UTC
There is nothing in the documentation about how to switch on the CommonMark parser. How to do that? 
Here is my markdown
```html
<div class="something" markdown="1" dir>

 ## Heading 2
 Some **bold** text.

</div>
``` 

so, [here is](https://marked.js.org/demo/?text=%3Cdiv%20class%3D%22something%22%20markdown%3D%221%22%20dir%3E%0A%0A%20%23%23%20Heading%202%0A%20Some%20**bold**%20text.%0A%0A%3C%2Fdiv%3E) it doesn't work at all, but here with CommonMark it [works correctly](https://spec.commonmark.org/dingus/)

Thanks in advance!

**Comment by joshbruce** [comment] 2018-05-11 13:54
Looks like there are two things at play here. To the first question, there is not, at this time, an explicit way to say "CommonMark" - it is under consideration. Having said that, the temporary logic is to explicitly set Pedantic and GFM to false.

I can confirm this does not seem to work. However, I can also confirm that [CommonMark Example 120](https://spec.commonmark.org/0.28/#example-120) does work [here](https://marked.js.org/demo/?text=%3Cdiv%20class%3D%22foo%22%3E%0A%0A*Markdown*%0A%0A%3C%2Fdiv%3E). It seems to be the inclusion of the header.

**Comment by styfle** [comment] 2018-05-13 19:08
This also seems to be related to #1263 since both are wrapping in html tags.

**Comment by styfle** [comment] 2018-08-17 14:33
To add to @joshbruce answer, you must disable heading ids since those are enabled by default. 
Related issue to change default options: #1280

The output for marked is identical (in this case) to commonmark if you set `headerIds: false`.

See the [USING_ADVANCED](https://marked.js.org/#/USING_ADVANCED.md) doc for more options.

I'll close this issue since this particular markdown renders properly now.

**Closed by styfle** 2018-08-17 14:33 UTC
Labels: L1 - broken, question
