### ISSUE TITLE
Star italics are mishandled around text in double quotes

### ISSUE THREAD

**Issue by octogonz** [markedjs/marked#1629] opened 2020-03-25 22:36 UTC
**Describe the bug**

CommonMark allows the `*` character to be used to italicize text.  Marked supports this, but not when the text contains double quotes.

**To Reproduce**

Consider this markdown input:

```
1. *"hello"* - INCORRECT
2. *"hello* - INCORRECT
3. *hello"* - correct
4. _"Hello"_ - correct
5. *'hello'* - correct
6. **"hello"** - correct
```
[Marked Demo](https://marked.js.org/demo/) renders the first two strings incorrectly.

**Expected behavior**

[CommonMark Demo](https://spec.commonmark.org/dingus/) renders it correctly:  Items 1 through 5 are italicized, and item 6 is boldfaced.

**Comment by UziTech** [comment] 2020-03-26 00:29
duplicate of #1358

**Closed by UziTech** 2020-03-26 00:29 UTC
