### ISSUE TITLE
Emphasized URL with underscores

### ISSUE THREAD

**Issue by p3k** [markedjs/marked#872] opened 2017-03-17 15:05 UTC
After upgrading marked from 0.3.3 to 0.3.4 I noticed a different output for the following call:

```
echo "_https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/_" | marked
```

This is was I got so far in marked 0.3.3 – which is also what I would expect:

<p><em><a href="https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/">https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/</a></em></p>

```
<p><em><a href="https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/">https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/</a></em></p>
```

However, in marked 0.3.4 **and greater** the output becomes this:

<p>_<a href="https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/_">https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/_</a></p>

```
<p>_<a href="https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/_">https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/_</a></p>
```

Please also note that Github’s markdown implementation behaves like 0.3.3:

_https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/_

**Comment by phiggins42** [comment] 2017-05-24 02:15
came to file this same bug/regression. current test was @ 0.3.6 ... will move back to 0.3.3 it seems.

**Comment by joshbruce** [comment] 2017-12-25 20:10
#984

**Comment by Feder1co5oave** [comment] 2018-01-10 01:48
I'll just say that this is due to a change to the `em` inline rule:

```patch
@@ -454,7 +456,7 @@ var inline = {
   reflink: /^!?\[(inside)\]\s*\[([^\]]*)\]/,
   nolink: /^!?\[((?:\[[^\]]*\]|[^\[\]])*)\]/,
   strong: /^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,
-  em: /^\b_((?:__|[\s\S])+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,
+  em: /^\b_((?:[^_]|__)+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,
   code: /^(`+)\s*([\s\S]*?[^`])\s*\1(?!`)/,
   br: /^ {2,}\n(?!\s*$)/,
   del: noop,
```
First of all, autolinking of plain URLs is GFM matter. Markdown (commonmark) allows [autolinking](http://spec.commonmark.org/0.28/#autolink) of URIs wrapped inside `<..>`.
Still, even 

    _<https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/>_

gets parsed to

    <p>_<a href="https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/">https://reddit.com/r/science/comments/5yde1e/its_official_time_crystals_are_a_new_state_of/</a>_</p>

and this is not correct. This is a tricky one.

Whenever underscores are present in URLs, it is advisable to use [reflinks](http://spec.commonmark.org/0.28/#example-498).

**Comment by Feder1co5oave** [comment] 2018-01-10 01:50
@joshbruce I would re-open this one and put it under category 'emphasize'.

**Comment by joshbruce** [comment] 2018-01-10 02:13
@Feder1co5oave: Re-opening. Putting under "links" for now. Would like avoid creating a category for individual HTML elements. That's why we have "lists" instead of "description lists", yeah?

Maybe inline and block would make sense as categories as well. I only created the initial categories because there were more than 5 or 6 issues revolving around that topic.

**Comment by UziTech** [comment] 2018-12-05 22:30
this seems to be fixed in the latest version of marked. [demo](https://marked.js.org/demo/?outputType=html&text=_https%3A%2F%2Freddit.com%2Fr%2Fscience%2Fcomments%2F5yde1e%2Fits_official_time_crystals_are_a_new_state_of%2F_&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)

**Closed by UziTech** 2018-12-05 22:30 UTC
Labels: category: links
