### ISSUE TITLE
Incompatibility between links wrapped in asterisks, pedantic, and GFM

### ISSUE THREAD

**Issue by simov** [markedjs/marked#1410] opened 2019-01-14 17:58 UTC
**Describe the bug**

I have a named link, that I want wrapped in asterisks, essentially making it italic.

**To Reproduce**

```markdown
- italic
  - [*named link*][some-url]
  - *[named link][some-url]*
  - [_named link_][some-url]
  - _[named link][some-url]_
- bold
  - [**named link**][some-url]
  - **[named link][some-url]**
  - [__named link__][some-url]
  - __[named link][some-url]__
- bold italic
  - [***named link***][some-url]
  - ***[named link][some-url]***
  - [___named link___][some-url]
  - ___[named link][some-url]___
  - [*__named link__*][some-url]
  - [__*named link*__][some-url]
  - __*[named link][some-url]*__
- code
  - [`named link`][some-url]
- code italic
  - *[`named link`][some-url]*
  - [*`named link`*][some-url]
  - _[`named link`][some-url]_
  - [_`named link`_][some-url]
- code bold
  - **[`named link`][some-url]**
  - [**`named link`**][some-url]
  - __[`named link`][some-url]__
  - [__`named link`__][some-url]
- code bold italic
  - [***`named link`***][some-url]
  - ***[`named link`][some-url]***
  - [___`named link`___][some-url]
  - ___[`named link`][some-url]___
  - [*__`named link`__*][some-url]
  - [__*`named link`*__][some-url]
  - __*[`named link`][some-url]*__
```

The offending lines are:

```markdown
- *[named link][some-url]*
- ***[named link][some-url]***
- __*[named link][some-url]*__
- *[`named link`][some-url]*
- ***[`named link`][some-url]***
- __*[`named link`][some-url]*__
```

Enabling the `pedantic` option fixes this issue, but at the same time it breaks lots of other stuff, like GFM tables and strikethrough. Also note that I only tested with named links, but it may be broken for other types of links as well.

**Expected behavior**

Well, I'm looking at the exact same example using Remark - another popular parser, that I think was forked out of Marked back then, and everything renders correctly.

Let me know if I need to provider more information.

**Comment by styfle** [comment] 2019-01-14 18:40
Thanks this looks like a bug.

Compare the output from [marked](https://marked.js.org/demo/?text=-%20italic%0A%20%20-%20%5B*named%20link*%5D%5Bsome-url%5D%0A%20%20-%20*%5Bnamed%20link%5D%5Bsome-url%5D*%0A%20%20-%20%5B_named%20link_%5D%5Bsome-url%5D%0A%20%20-%20_%5Bnamed%20link%5D%5Bsome-url%5D_%0A-%20bold%0A%20%20-%20%5B**named%20link**%5D%5Bsome-url%5D%0A%20%20-%20**%5Bnamed%20link%5D%5Bsome-url%5D**%0A%20%20-%20%5B__named%20link__%5D%5Bsome-url%5D%0A%20%20-%20__%5Bnamed%20link%5D%5Bsome-url%5D__%0A-%20bold%20italic%0A%20%20-%20%5B***named%20link***%5D%5Bsome-url%5D%0A%20%20-%20***%5Bnamed%20link%5D%5Bsome-url%5D***%0A%20%20-%20%5B___named%20link___%5D%5Bsome-url%5D%0A%20%20-%20___%5Bnamed%20link%5D%5Bsome-url%5D___%0A%20%20-%20%5B*__named%20link__*%5D%5Bsome-url%5D%0A%20%20-%20%5B__*named%20link*__%5D%5Bsome-url%5D%0A%20%20-%20__*%5Bnamed%20link%5D%5Bsome-url%5D*__%0A-%20code%0A%20%20-%20%5B%60named%20link%60%5D%5Bsome-url%5D%0A-%20code%20italic%0A%20%20-%20*%5B%60named%20link%60%5D%5Bsome-url%5D*%0A%20%20-%20%5B*%60named%20link%60*%5D%5Bsome-url%5D%0A%20%20-%20_%5B%60named%20link%60%5D%5Bsome-url%5D_%0A%20%20-%20%5B_%60named%20link%60_%5D%5Bsome-url%5D%0A-%20code%20bold%0A%20%20-%20**%5B%60named%20link%60%5D%5Bsome-url%5D**%0A%20%20-%20%5B**%60named%20link%60**%5D%5Bsome-url%5D%0A%20%20-%20__%5B%60named%20link%60%5D%5Bsome-url%5D__%0A%20%20-%20%5B__%60named%20link%60__%5D%5Bsome-url%5D%0A-%20code%20bold%20italic%0A%20%20-%20%5B***%60named%20link%60***%5D%5Bsome-url%5D%0A%20%20-%20***%5B%60named%20link%60%5D%5Bsome-url%5D***%0A%20%20-%20%5B___%60named%20link%60___%5D%5Bsome-url%5D%0A%20%20-%20___%5B%60named%20link%60%5D%5Bsome-url%5D___%0A%20%20-%20%5B*__%60named%20link%60__*%5D%5Bsome-url%5D%0A%20%20-%20%5B__*%60named%20link%60*__%5D%5Bsome-url%5D%0A%20%20-%20__*%5B%60named%20link%60%5D%5Bsome-url%5D*__%0A%0A%0A%5Bsome-url%5D%3A%20https%3A%2F%2Fwww.google.com&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D) with the output from [commonmark](https://spec.commonmark.org/dingus/?text=-%20italic%0A%20%20-%20%5B*named%20link*%5D%5Bsome-url%5D%0A%20%20-%20*%5Bnamed%20link%5D%5Bsome-url%5D*%0A%20%20-%20%5B_named%20link_%5D%5Bsome-url%5D%0A%20%20-%20_%5Bnamed%20link%5D%5Bsome-url%5D_%0A-%20bold%0A%20%20-%20%5B**named%20link**%5D%5Bsome-url%5D%0A%20%20-%20**%5Bnamed%20link%5D%5Bsome-url%5D**%0A%20%20-%20%5B__named%20link__%5D%5Bsome-url%5D%0A%20%20-%20__%5Bnamed%20link%5D%5Bsome-url%5D__%0A-%20bold%20italic%0A%20%20-%20%5B***named%20link***%5D%5Bsome-url%5D%0A%20%20-%20***%5Bnamed%20link%5D%5Bsome-url%5D***%0A%20%20-%20%5B___named%20link___%5D%5Bsome-url%5D%0A%20%20-%20___%5Bnamed%20link%5D%5Bsome-url%5D___%0A%20%20-%20%5B*__named%20link__*%5D%5Bsome-url%5D%0A%20%20-%20%5B__*named%20link*__%5D%5Bsome-url%5D%0A%20%20-%20__*%5Bnamed%20link%5D%5Bsome-url%5D*__%0A-%20code%0A%20%20-%20%5B%60named%20link%60%5D%5Bsome-url%5D%0A-%20code%20italic%0A%20%20-%20*%5B%60named%20link%60%5D%5Bsome-url%5D*%0A%20%20-%20%5B*%60named%20link%60*%5D%5Bsome-url%5D%0A%20%20-%20_%5B%60named%20link%60%5D%5Bsome-url%5D_%0A%20%20-%20%5B_%60named%20link%60_%5D%5Bsome-url%5D%0A-%20code%20bold%0A%20%20-%20**%5B%60named%20link%60%5D%5Bsome-url%5D**%0A%20%20-%20%5B**%60named%20link%60**%5D%5Bsome-url%5D%0A%20%20-%20__%5B%60named%20link%60%5D%5Bsome-url%5D__%0A%20%20-%20%5B__%60named%20link%60__%5D%5Bsome-url%5D%0A-%20code%20bold%20italic%0A%20%20-%20%5B***%60named%20link%60***%5D%5Bsome-url%5D%0A%20%20-%20***%5B%60named%20link%60%5D%5Bsome-url%5D***%0A%20%20-%20%5B___%60named%20link%60___%5D%5Bsome-url%5D%0A%20%20-%20___%5B%60named%20link%60%5D%5Bsome-url%5D___%0A%20%20-%20%5B*__%60named%20link%60__*%5D%5Bsome-url%5D%0A%20%20-%20%5B__*%60named%20link%60*__%5D%5Bsome-url%5D%0A%20%20-%20__*%5B%60named%20link%60%5D%5Bsome-url%5D*__%0A%0A%0A%5Bsome-url%5D%3A%20https%3A%2F%2Fwww.google.com).

**Comment by simov** [comment] 2019-01-15 10:00
@styfle I think wrapping up your links with asterisks as pretty common, because that's the only way the editors can apply the correct style to that link.

I only use HTML tags in my markdown documents as a last resort.

**Comment by styfle** [comment] 2019-01-15 15:50
Agreed, this is a bug 👍 

Would you like to submit a PR to fix it? 😃

**Comment by simov** [comment] 2019-01-15 16:17
Well, you got me! I'm not familiar with this library, but I have a [browser extension](https://github.com/simov/markdown-viewer) that can be used as a constant source of annoyances for you. :smile:

**Comment by UziTech** [comment] 2019-03-11 14:21
related to #1284

**Comment by x13machine** [comment] 2019-03-13 20:25
It appears to be something wrong with this regex https://github.com/markedjs/marked/blob/master/lib/marked.js#L545 I'll see if I can fix it today.

**Comment by UziTech** [comment] 2019-03-13 21:47
@x13machine The problem is that an `em` can't end inside a link so it will be difficult to find an em with just a regular expression.

so `*[link*](url)*` should be 
```html
<p><em><a href="url">link*</a></em></p>
```

not

```html
<p><em>[link</em>](url)*</p>
```

so after finding an ending `*` or `_` you will have to figure out if it is in a valid link, and if it is find the next ending `*` or `_`

**Comment by x13machine** [comment] 2019-03-13 22:38
so the regex should replace with a function?

**Comment by UziTech** [comment] 2019-03-14 00:36
It should be something like the way we check for nested parentheses in a link. The regex should grab more than it needs if the end is in square brackets or parentheses then the lexer will run it through a function and find the actual end.

**Comment by x13machine** [comment] 2019-03-14 07:48
Why does group 3 match  `_[link_](url)_` while group 5 not match  `*[link*](url)*` ? I going to refresh up on regex.

**Comment by UziTech** [comment] 2019-03-14 14:25
ya the regex doesn't treat `_` and `*` the same but it should.

**Comment by crystalfp** [comment] 2019-08-03 14:42
A very similar problem is still here ("marked": "^0.7.0"):
```

const markdown = `Some say these principles require a revolution to be realized. Others
say we need massive innovation to make positive education futures a
reality. We believe we need both, or as Ronald van den Hoff (2013) says:
“What we really need is an *innovution*\!” (p. 236). And, this is our
noble quest: To *innovute* with not only our ideas, but also the
purposive applications of what we have learned through our individual
efforts, and together, globally.

Education Futures. *<http://www.knowmadsociety.com>*
`;

const marked = require("marked");

const html = marked(markdown, {smartypants: true, headerIds: false});

console.log(html);
```
The `*` around the `<...>` is not translated. The strange thing is that in this example the two pairs of asterisks in the text are correctly translated, instead in my application (exactly same text) the second and third asterisks are not translated. 

Thanks for looking!

**Comment by crystalfp** [comment] 2019-08-03 14:45
The second error can be reproduced in the editor [editor](https://marked.js.org/demo/?text=Some%20say%20these%20principles%20require%20a%20revolution%20to%20be%20realized.%20Others%0Asay%20we%20need%20massive%20innovation%20to%20make%20positive%20education%20futures%20a%0Areality.%20We%20believe%20we%20need%20both%2C%20or%20as%20Ronald%20van%20den%20Hoff%20(2013)%20says%3A%0A%E2%80%9CWhat%20we%20really%20need%20is%20an%20*innovution*%5C!%E2%80%9D%20(p.%20236).%20And%2C%20this%20is%20our%0Anoble%20quest%3A%20To%20*innovute*%20with%20not%20only%20our%20ideas%2C%20but%20also%20the%0Apurposive%20applications%20of%20what%20we%20have%20learned%20through%20our%20individual%0Aefforts%2C%20and%20together%2C%20globally.%0A%0AEducation%20Futures.%20*%3Chttp%3A%2F%2Fwww.knowmadsociety.com%3E*%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by calculuschild** [comment] 2020-12-10 03:39
Closing this since all of the cases in the OP appear to be working correctly now as of , as well as the later issue by @crystalfp.

**Closed by calculuschild** 2020-12-10 03:39 UTC
Labels: L2 - annoying, category: inline elements, category: mixed content
