### ISSUE TITLE
exports is not defined at marked.min.js:6

### ISSUE THREAD

**Issue by Dipeshpal** [markedjs/marked#2284] opened 2021-11-13 07:30 UTC
**Marked version: latest**

**Describe the bug**
**exports is not defined**

marked.min.js:6 Uncaught ReferenceError: exports is not defined
    at marked.min.js:6
k.html?_ijt=rg884u0cuo8hg8i4rk7cutu18i:12 Uncaught TypeError: marked.parse is not a function
    at k.html:12
k.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
DevTools failed to load source map: Could not load content for chrome-extension://ljngjbnaijcbncmcnjfhigebomdlkcjo/content-script/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**To Reproduce**
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Marked in the browser</title>
</head>
<body>
  <div id="content"></div>
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <script>
    document.getElementById('content').innerHTML =
      marked.parse('# Marked in browser\n\nRendered by **marked**.');
  </script>
</body>
</html>
```

Check here: https://thetechport.in/article/122_bgmi-diwali-offers

**Comment by UziTech** [comment] 2021-11-13 08:15
duplicate of #2282

**Closed by UziTech** 2021-11-13 08:15 UTC
