### ISSUE TITLE
Add an extension without modifying the global object

### ISSUE THREAD

**Issue by sashee** [markedjs/marked#2791] opened 2023-05-02 09:51 UTC
**Describe the feature**
Before the current release I could define a highlighter in the ```options``` but that is now deprecated with an extension taking its place.

The only way I could find to register an extension is to use ```marked.use``` but that modifies the ```marked``` object so that all subsequent calls will use the extension.

I'd like to have a non-mutating way to register extensions, for example by having an ```extensions``` field in the options, or something similar.

**Why is this feature necessary?**
My highlighter function is rather complex and I need to construct it dynamically for the given ```marked``` run. It works when it's passed in the ```options``` but an extension modifies the global object.

**Describe alternatives you've considered**

**Comment by UziTech** [comment] 2023-05-02 14:24
Duplicate of #907

**Closed by UziTech** 2023-05-02 14:24 UTC
