### ISSUE TITLE
Render bullet-pointed incorrectly

### ISSUE THREAD

**Issue by hzoou** [markedjs/marked#2851] opened 2023-06-19 03:09 UTC
**Marked version:**
v5.0.4

**Describe the bug**
![스크린샷 2023-06-19 오후 12 10 02](https://github.com/markedjs/marked/assets/50589682/459bd281-035e-4238-a92d-32bdba83b297)
[demo](https://marked.js.org/demo/?text=-%20title%0A%20%20-%20&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=5.1.0)

If there is no text, it will be exposed as heading. .. 

https://github.com/markedjs/marked/issues/2819

**Comment by UziTech** [comment] 2023-06-19 04:16
Duplicate of #2832

**Closed by UziTech** 2023-06-19 04:16 UTC
