### ISSUE TITLE
Bold and italic 

### ISSUE THREAD

**Issue by novito** [markedjs/marked#1424] opened 2019-02-19 17:24 UTC
**Describe the bug**
When combining bold and italics, marked is not properly displaying the markdown.

**To Reproduce**

Reproducible steps by example:

1. [Marked Demo](https://marked.js.org/demo/?text=**hello%20**_**how**_**%20are%20you**%0A&options=**hola%20**_**que**_**%20tal**%0A&version=master) Wrong output
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=**hello%20**_**how**_**%20are%20you**) Correct output

**Expected behavior**
Problem: As you can see, the marked demo doesn't output properly the bold and italics, in comparison to the CommonMark Demo. 
Expected behavior: The marked output should be the same than the CommonMark.

**Comment by UziTech** [comment] 2019-02-19 17:31
The fix would be to use the spaces correctly

`**hello** _**how**_ **are you**`

**Comment by novito** [comment] 2019-02-19 17:35
@UziTech yep. Unfortunately the [RTE](https://react-rte.org/demo) I'm using seems to be outputting the spaces in that other way. It's not technically incorrect right? Should marked be able to know parse it similarly to what CommonMark is doing it? Happy to look into the code to put the fix in place if you want to point me where I should be looking at.

**Comment by UziTech** [comment] 2019-02-19 17:37
Yes it is a bug. PRs are always welcome.

Closing this as a duplicate of #1353

**Closed by UziTech** 2019-02-19 17:37 UTC
Labels: L2 - annoying, category: inline elements
