### ISSUE TITLE
Failed to render italic text when it begin with double quoutes

### ISSUE THREAD

**Issue by mdunisch** [markedjs/marked#1447] opened 2019-03-12 07:14 UTC
**Describe the bug**
Whereever a text begin with double quotes marked ignore the starting * to make this text italic.

**To Reproduce**
Here you see the wrong rendering:
[Marked Demo](https://marked.js.org/demo/?text=*%22How%20bad%20is%20the%20paypal-sdk%3F%22%20he%20asked%20me*%20%0A%0A*He%20said%3A%20%22An%20now%20it%20work%22*%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**
The hole text should be italic

**Comment by UziTech** [comment] 2019-03-12 12:20
Duplicate of #1358

**Closed by UziTech** 2019-03-12 12:20 UTC
