### ISSUE TITLE
Customize Lexer and Parser

### ISSUE THREAD

**Issue by janosh** [markedjs/marked#1890] opened 2020-12-24 08:48 UTC
### Describe the feature

Provide the ability to customize the Lexer and Parser.

### Why is this feature necessary?

Marked's current architecture is not amenable to certain extensions. I'd like to create an extension that supports custom attributes (like [remark-attr](https://github.com/arobase-che/remark-attr) and [markdown-it-attrs](https://github.com/arve0/markdown-it-attrs)):

```md
# Yeah{.success}
```

```html
<h1 class="success">Yeah</h1>
```

[Currently, I can only customize the Tokenizer and Renderer](https://marked.js.org/using_pro#renderer). This means, the call signature for rendering e.g. a link is fixed by the Parser to be `link(href, title, text) { ... }`. This leaves no room for passing in another argument `attrs` to render any attributes.

### Describe alternatives you've considered

Nothing good comes to mind.

**Comment by UziTech** [comment] 2020-12-24 15:16
Duplicate of #1693. 

#1872 is trying to fix it.

**Closed by UziTech** 2020-12-24 15:16 UTC

**Comment by janosh** [comment] 2020-12-24 15:23
If I understand correctly, #1872 only addresses the Lexer. With that merged, I would still be unable to create a custom renderer with the ability to pass around an additional argument for attributes, no?

**Comment by UziTech** [comment] 2020-12-24 15:29
Ya the idea is that you will be able to create your own tokenizers and renderers so you will be able to pass whatever you want. I'm not exactly sure how it will work out. The current implementation is very slow. If you want to help out we could use more input on it.

**Comment by janosh** [comment] 2020-12-25 10:40
I took a closer look at #1872. I'm afraid I don't understand marked internals enough to make useful speed-up suggestions. Happy to help though if there's something less sophisticated to do.
