### ISSUE TITLE
Integration with KaTeX

### ISSUE THREAD

**Issue by alexeypetrushin** [markedjs/marked#1582] opened 2019-12-14 20:07 UTC
**Marked version:0.8.0**

**Markdown flavor:** GitHub Flavored Markdown

**Proposal type:** other

## What pain point are you perceiving?

Can't render math formula

## What solution are you suggesting?

Provide integration wit KaTeX or others

## Question

I searched through issues - there are ~7 issues discussing math extensions and all of them are either open ended or refer to some other issue that also says nothing.

Is there any way to integrate marked with KaTeX or other Math formatters? If so  where can I find instruction how to do that? If not - any plans to do it and any timelines?

Thanks.

**Comment by UziTech** [comment] 2019-12-14 22:47
You can check out [marked-katex](https://www.npmjs.com/package/marked-katex) or create your own renderer like https://github.com/markedjs/marked/issues/1538#issuecomment-526189561

We will not add this to marked since it is not a part of the spec.

I'm closing this since it is a duplicate of the other 7 issues you found.

**Closed by UziTech** 2019-12-14 22:47 UTC
Labels: NFE - new feature (should be an extension)

**Comment by julien-c** [comment] 2020-06-19 10:46
Also see https://github.com/markedjs/marked/pull/799#issuecomment-646568986

**Comment by UziTech** [comment] 2022-09-07 14:36
Katex has been something people have been asking for for a while so I just created an extension and published it to npm. [marked-katex-extension](https://www.npmjs.com/package/marked-katex-extension)

**Comment by calculuschild** [comment] 2022-09-07 15:05
We previously discussed maintaining a small list of known extensions. https://github.com/markedjs/marked/discussions/2321#discussioncomment-1800936

It is worth putting that together as part of the docs now that we have a few floating around out there?

**Comment by UziTech** [comment] 2022-09-07 21:03
@calculuschild ya it would be nice to have a list of known extensions in the docs
