### ISSUE TITLE
Handle [!NOTE]

### ISSUE THREAD

**Issue by Rossb0b** [markedjs/marked#3106] opened 2023-11-25 23:10 UTC
👋 

**Describe the feature**
It looks like [those](https://github.com/orgs/community/discussions/16925) are not handled actually.

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.

**Why is this feature necessary?**
Cuz it's marked ! :)

**Describe alternatives you've considered**
Self implementation

**Comment by UziTech** [comment] 2023-11-25 23:26
Duplicate of #3010

The [marked-alert](https://www.npmjs.com/package/marked-alert) extension can be used for this.

**Closed by UziTech** 2023-11-25 23:26 UTC
