### ISSUE TITLE
allow adding new rules using marked.use

### ISSUE THREAD

**Issue by upupming** [markedjs/marked#1863] opened 2020-12-05 05:13 UTC
Thanks for your great work, marked.js is really cool.

**Describe the feature**

As a plugin developer, you may need to add new rules to extend the functionality of marked.js. However, I cannot figure out how to define my rules with `marked.use` after looking into both the documentation and the source code.

The documentation [said](https://marked.js.org/using_pro#tokenizer):

> Example: Overriding default codespan tokenizer to include LaTeX.
> ```js
> // Create reference instance
> const marked = require('marked');
>
> // Override function
> const tokenizer = {
>   codespan(src) {
>     const match = src.match(/\$+([^\$\n]+?)\$+/);
>     if (match) {
>       return {
>         type: 'codespan',
>         raw: match[0],
>         text: match[1].trim()
>       };
>     }
>
>     // return false to use original codespan tokenizer
>     return false;
>   }
> };
>
> marked.use({ tokenizer });
>
> // Run marked
> console.log(marked('$ latex code $\n\n` other code `'));
> ```

This is totally a good way to implement the LaTeX feature in marked.js, however, the user has to put all math in the codespan tag, and it doesn't follow the [pandoc standard](https://pandoc.org/MANUAL.html#math), which is widely used by other software. If I render a markdown file created by another software, it will fail to parse the LaTeX code.

In [markdown-it](https://github.com/markdown-it/markdown-it), one can simply add custom rules by modifying the `MarkdownIt` object passed in the `use` function, you can see [here](https://markdown-it.github.io/markdown-it/#Ruler.after) and [here](https://markdown-it.github.io/markdown-it/#Renderer.prototype.rules) how to add new rules . For example, the main logic of [markdown-it-katex](https://github.com/waylonflinn/markdown-it-katex/) is like below:

```ts
function math_plugin(md: MarkdownIt, options) {
  md.inline.ruler.after('escape', 'math_inline', math_inline);
  md.block.ruler.after('blockquote', 'math_block', math_block, {
    alt: ['paragraph', 'reference', 'blockquote', 'list'],
  });
  md.renderer.rules.math_inline = inlineRenderer;
  md.renderer.rules.math_block = blockRenderer;
}

var md = require('markdown-it')();
md.use(mk);
```

Is there any way to extend marked.js with a plugin (`marked.use{...}`) and add new rules without modifying the source code of marked.js? For example, expose the `marked` object to a plugin, and the plugin can modify the `marked.Lexer`

**Why is this feature necessary?**

Allow adding custom syntax (math, footnote, etc.) to mark.js by third party plugins.

**Comment by UziTech** [comment] 2020-12-05 05:41
duplicate of #1693

**Closed by UziTech** 2020-12-05 05:41 UTC
