### ISSUE TITLE
Uncaught TypeError: Cannot parse `> 1\n> > 2`

### ISSUE THREAD

**Issue by xovel** [markedjs/marked#1500] opened 2019-06-09 13:27 UTC
```
> 1
> > 2
```

> Uncaught TypeError: Cannot read property 'type' of undefined

See: [ `> 1\n> > 2`](https://marked.js.org/demo/?outputType=html&text=%3E%201%0A%3E%20%3E%202&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

and, it's done well in `v0.6.2`.

**********

> 1
> > 2

**********

**Comment by UziTech** [comment] 2019-06-09 16:23
Duplicate of #1494

**Closed by UziTech** 2019-06-09 16:23 UTC

**Comment by xovel** [comment] 2019-06-09 17:40
Ooops, I forgot it....
