### ISSUE TITLE
Problem with spaces as new-line after bold/italics followed by a period

### ISSUE THREAD

**Issue by fditolla** [markedjs/marked#1711] opened 2020-06-17 14:51 UTC
Marked does not handle correctly bold and italics delimiters when followed by a period and 2 used spaces to denote newline. 

With the following test data (all lines are terminated by two spaces), line 1 and 5 do not comply with the 2 spaces rule=new-line:
--- test data start ---
line 1 **bold followed by period**.  
line 2  

line 3 __bold follwed by period__.  
line 4  

line 5 **bold**  
line 6  

line 7 *italic followed by period*.  
line 8  

line 9 _italic follwed by period_.  
line 10  

line 11 *italic*  
line 12  

line 13 text followed by period.  
line 14  

line 15 text  
line 16  

--- end ---
this is rendered by Marked (version 1.1.0) without a &lt;br&gt; between line pairs 
* 1 and 2
* 3 and 4
* 7 and 8
* 9 and 10.

**Comment by UziTech** [comment] 2020-06-17 15:08
duplicate of #1699

**Closed by UziTech** 2020-06-17 15:08 UTC
