### ISSUE TITLE
Touching italic/bold doesn't render right (v1.1.1 regression)

### ISSUE THREAD

**Issue by fredck** [markedjs/marked#1754] opened 2020-09-03 08:38 UTC
When italic and bold are touching, italic is ignored:

```
// Input
_te_**st**

// Expected output
<p><em>te</em><strong>st</strong></p>

// Actual output (wrong)
<p>_te_<strong>st</strong></p>
```

This was [working with v1.1.0](https://marked.js.org/demo/?outputType=html&text=_te_**st**&options=&version=1.1.0) and is [not working with v1.1.1](https://marked.js.org/demo/?outputType=html&text=_te_**st**&options=&version=1.1.1).

**Comment by styfle** [comment] 2020-09-03 13:40
Thanks for reporting this issue! It looks like it was fixed in v0.6.0 and broke in v1.1.1 🤔 

This was mentioned in #1353 years ago but I'll elevate this to L1 since it was working for a couple years and regression in the latest release 👍 

Would you like to create a PR to fix it? 🙂

**Comment by calculuschild** [comment] 2020-09-04 03:59
I suspect this can be fixed in this line by adding an asterisk to the "punctuation" group. Haven't tested it, but probably the place to look.
https://github.com/markedjs/marked/blob/a41d8f9aa69a4095aedae93c6e6ee5522a588217/src/rules.js#L182
```
endUnd: /[^\s]_(?!_)(?:(?=[*punctuation\s])|$)/ // last char can't be a space, and final _ must preceed punct or \s (or endline) 
```
Any PR should include tests for all valid permutations of this since evidently this has been fixed and broken over the years without being detected. i.e.: (all of these seem to generate valid tags on both sides within github)

1. `_te_**st**` _te_**st**
2. `_te_*st*` _te_*st*
3. `*te*__st__` *te*__st__
4. `*te*_st_` *te*_st_
5. `__te__*st*` __te__*st*
6. `**te**_st_` **te**_st_
7. `**te**__st__` **te**__st__
8. `__te__**st**` __te__**st**

**Comment by fredck** [comment] 2020-09-04 13:49
> I suspect this can be fixed in this line by adding an asterisk to the "punctuation" group.

Found a few lines later: 

https://github.com/markedjs/marked/blob/a41d8f9aa69a4095aedae93c6e6ee5522a588217/src/rules.js#L191-L192

**Comment by fredck** [comment] 2020-09-04 13:53
> Would you like to create a PR to fix it? 🙂

I was hoping for @UziTech to jump in, as this regression may have been introduced by their PR (#1686). It may be more difficult for me, but I may try to check this in the future.

**Comment by UziTech** [comment] 2020-09-04 15:57
I can take a look at it this weekend. Thanks for the test cases @calculuschild.

**Comment by UziTech** [comment] 2020-09-04 16:35
I started PR #1755 to fix this with @calculuschild's suggestion.

There are a few [other cases](https://github.com/markedjs/marked/pull/1755/files#diff-8034012747f7688e448cb57fc9900091R7) I think we should test that are still failing such as `_te___st__` => `<em>te___st</em>_`

Or we could just consider these unspecified behavior.

**Comment by calculuschild** [comment] 2020-09-04 17:35
> such as _te___st__ => <em>te___st</em>_

I don't see this case exactly in the GFM spec; the closest being [Example #424](https://github.github.com/gfm/#example-424). There's the comment below Test #420 that says an emphasis delimiter can't exist if the size of the delimiter runs containing the opening and closing delimiters sums to a multiple of 3, so in this case:

`1te234st__` means we could have `<em>te</em><strong>st</strong>` but not `1te___st23` => `<em>te___st_</em>` which is what we have now.

I guess the best answer is to look at [Babelmark](https://johnmacfarlane.net/babelmark2/?text=_te___st__) which shows literally every implementation has a different answer. Commonmark is probably the "most accurate" though, and they get around the multiples of 3 rule by excluding the final underscore as per [Example #467](https://github.github.com/gfm/#example-467). Markdown 1.1.1 is probably the second best out of that list though :).

**Comment by UziTech** [comment] 2020-09-04 18:17
I would like to get marked to follow common mark on all of these examples.

[demo](https://spec.commonmark.org/dingus/?text=_te_*st*%0A%0A_te_**st**%0A%0A_te__st_%0A%0A_te___st__%0A%0A%0A*te**st*%0A%0A*te***st**%0A%0A*te*_st_%0A%0A*te*__st__%0A%0A%0A__te__*st*%0A%0A__te__**st**%0A%0A__te___st_%0A%0A__te____st__%0A%0A%0A**te***st*%0A%0A**te****st**%0A%0A**te**_st_%0A%0A**te**__st__%0A)

| markdown | commonmark |
|----|---|
| `_te_*st*` | `<em>te</em><em>st</em>`|
|`_te_**st**` | `<em>te</em><strong>st</strong>`|
|`_te__st_` | `<em>te__st</em>`|
|`_te___st__` | `<em>te___st</em>_`|
|`*te**st*` | `<em>te**st</em>`|
|`*te***st**` | `<em>te</em><strong>st</strong>`|
|`*te*_st_` | `<em>te</em><em>st</em>`|
|`*te*__st__` | `<em>te</em><strong>st</strong>`|
|`__te__*st*` | `<strong>te</strong><em>st</em>`|
|`__te__**st**` | `<strong>te</strong><strong>st</strong>`|
|`__te___st_` | `_<em>te___st</em>`|
|`__te____st__` | `<strong>te____st</strong>`|
|`**te***st*` | `<strong>te</strong><em>st</em>`|
|`**te****st**` | `<strong>te****st</strong>`|
|`**te**_st_` | `<strong>te</strong><em>st</em>`|
|`**te**__st__` | `<strong>te</strong><strong>st</strong>`|

**Comment by UziTech** [comment] 2020-09-04 18:21
#1755 already passes all of the tests in https://github.com/markedjs/marked/issues/1754#issuecomment-686889029 but to pass the rest might require a change in the tokenizer.

**Closed** 2020-09-18 00:40 UTC
Labels: L1 - broken, category: inline elements, category: mixed content
