### ISSUE TITLE
GFM underscore parsing is broken

### ISSUE THREAD

**Issue by javoire** [markedjs/marked#491] opened 2014-09-22 11:45 UTC
``` markdown
To recap on_our_use_case
```

becomes
![screen shot 2014-09-22 at 13 43 11](https://cloud.githubusercontent.com/assets/642869/4355542/cb64dfde-424d-11e4-969d-218f9334dbe6.png)

And it shouldn't, according to https://help.github.com/articles/github-flavored-markdown#multiple-underscores-in-words. The result should be the same as the input:

```
To recap on_our_use_case
```

Cheers,
JD

**Comment by Feder1co5oave** [comment] 2018-01-25 21:28
Can't reproduce this at 33b444c
@joshbruce can close

**Comment by joshbruce** [comment] 2018-04-13 18:56
Closing as I believe this will be fixed via spec-compliance. See #1106 and #1216

**Closed** 2018-04-17 14:11 UTC
