### ISSUE TITLE
I use typescript, therefore I need the new version declaration file.

### ISSUE THREAD

**Issue by ten-ltw** [markedjs/marked#2269] opened 2021-11-05 08:31 UTC
Hi,

I found the latest @types/marked in npm is `3.0.2`.
It's the type definitions for Marked 3.0.
And I upgrade marked to 4.0, the @types/marked 3.0.2 is not work any more.

So I think maybe we can serve the typescript declaration file in npm.

**Comment by UziTech** [comment] 2021-11-05 13:41
Duplicate of #2265

**Closed by UziTech** 2021-11-05 13:41 UTC
