### ISSUE TITLE
Inconsistent grammar behavior.(Lexer)

### ISSUE THREAD

**Issue by WenyaoL** [markedjs/marked#2774] opened 2023-04-04 15:36 UTC
**Marked version:**
"marked": "^4.3.0",

**Describe the bug**
When passing an empty object to the Lexer, the del tokenizer becomes invalid
![360截图16261010968994](https://user-images.githubusercontent.com/65602393/229842152-ec0d9f23-3b48-4d7f-9934-397c6b768247.png)

**To Reproduce**
```ts
import { Lexer, Parser} from 'marked' //origin marked
const fontMarkdownText = `**bold font**\`codeInline font\`*em font*~~deleteLine font~~**bold + ~~deleteLine~~ font**`
const lexer = new Lexer({})
const lexer2 = new Lexer(null)
const lexer3 = new Lexer()

const tokens = lexer.lex(fontMarkdownText)//find error
const tokens2 = lexer2.lex(fontMarkdownText)
const tokens3 = lexer3.lex(fontMarkdownText)
console.log(tokens);
console.log(tokens2);
console.log(tokens3);

const parser = new Parser()
const html = parser.parse(tokens)
const html2 = parser.parse(tokens2)
const html3 = parser.parse(tokens3)
```

**Expected behavior**
The behavior of `new Lexer({})` and `new Lexer()` has always been

**Comment by UziTech** [comment] 2023-04-04 16:25
This is intended behavior. The options object that you are passing in (`{}`) essentially sets all options to undefined. The options are not merged. So you are turning off `del` tokenizer the same as setting `gfm: false`.

`del` is not in the common mark spec it is an extension in GFM.

**Closed as completed** 2023-04-04 17:12 UTC
Labels: works as intended
