### ISSUE TITLE
Invalid regular expression in lower chrome

### ISSUE THREAD

**Issue by Vivapercuore** [markedjs/marked#3147] opened 2023-12-29 10:45 UTC
**Marked version:11.1.0

**Describe the bug**
![image](https://github.com/markedjs/marked/assets/30725659/2f7c4e72-5cef-4504-b8af-5496686cccc3)
![image](https://github.com/markedjs/marked/assets/30725659/39a4a9b8-93c9-4aa4-a0a0-a8ca249071ff)

**To Reproduce**
in low version chrome, like : 64.0 54.0

**Expected behavior**
It seems that some advanced regular syntax used is not supported in lower versions of Chrome

we need change the regExp code?

**Comment by UziTech** [comment] 2023-12-29 15:17
Duplicate of #3133

**Closed by UziTech** 2023-12-29 15:17 UTC

**Comment by UziTech** [comment] 2024-03-12 13:24
Good point. We can change it to a regular expression and building it should work the same.

**Comment by Vivapercuore** [comment] 2024-04-03 06:49
should we reopen this issues?

**Comment by UziTech** [comment] 2024-04-03 06:59
I don't think this is an issue we want to fix. We do not plan on supporting browsers that old. Even if we could fix it without slowing down marked on newer browsers we wouldn't have a way to test it and prevent regressions in the future.

**Comment by UziTech** [comment] 2024-04-03 07:01
If you need to support browsers that old I would suggest forking marked to make the changes and keep the fork up to date with other changes. Or use something like [yarn patch](https://yarnpkg.com/cli/patch) to make changes to marked in your repo.

**Comment by Vivapercuore** [comment] 2024-04-07 03:56
> 我认为这不是我们想要解决的问题。我们不打算支持那么旧的浏览器。即使我们可以修复它，而不会在较新的浏览器上标记速度减慢，我们也无法对其进行测试并防止将来出现回归。



> I don't think this is an issue we want to fix. We do not plan on supporting browsers that old. Even if we could fix it without slowing down marked on newer browsers we wouldn't have a way to test it and prevent regressions in the future.

sad to hear that
it‘s difficult for me to persuade the team to upgrade marked from 4.x to lastest with this problem，we can't ingore this Error reporting，even rather stay 4.x
