### ISSUE TITLE
link with quotes renderer error

### ISSUE THREAD

**Issue by uv-w** [markedjs/marked#1820] opened 2020-11-12 11:08 UTC
**Marked version:**
1.2.3
**Describe the bug**

link with quotes renderer error

**To Reproduce**

![image](https://user-images.githubusercontent.com/17735161/98932488-5af03080-251a-11eb-87ba-de444cee4af0.png)

https://marked.js.org/demo/?text=%22%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5%EF%BC%9Ahttp%3A%2F%2Fwww.baidu.com%22&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

**Comment by UziTech** [comment] 2020-11-12 14:32
http://www.baidu.com"duplicate of #1716

**Closed by UziTech** 2020-11-12 14:32 UTC
