### ISSUE TITLE
Crash on table like content in heading, followed by a list with continuation

### ISSUE THREAD

**Issue by ChristianMurphy** [markedjs/marked#2278] opened 2021-11-11 18:30 UTC
**Marked version:**

4.0.1

**Describe the bug**

Marked crashes when parsing file with error `TypeError: Cannot read properties of undefined (reading 'trim')`

**To Reproduce**

write the following file to _test.js_

```js
const marked = require("marked");

const source = `\\|
-
*
	`

console.log(marked.parse(source));
```

run `node test.js`

result is

```
marked/lib/marked.cjs:2600
      throw e;
      ^

TypeError: Cannot read properties of undefined (reading 'trim')
Please report this to https://github.com/markedjs/marked.
```

Issue can also be seen in the demo
https://marked.js.org/demo/?text=%5C%7C%0A-%0A*%0A%09&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.0.1

**Expected behavior**

No error is thrown (https://spec.commonmark.org/dingus/?text=%5C%7C%0A-%0A*%0A%09)

**Comment by ChristianMurphy** [comment] 2021-11-11 19:46
The issue appears to be specific to GFM mode [demo example without GFM](https://marked.js.org/demo/?text=%5C%7C%0A-%0A*%0A%09&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20false%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.0.1).
It appears to affect releases between 3.0.0-4.0.1 [demo example with 3.0.0](https://marked.js.org/demo/?text=%5C%7C%0A-%0A*%0A%09&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=3.0.0)

**Comment by calculuschild** [comment] 2021-11-11 19:52
I suspect this is the same issue as https://github.com/markedjs/marked/issues/2249

**Comment by UziTech** [comment] 2021-11-12 06:31
ya this seems like a duplicate of #2249

**Closed by UziTech** 2021-11-12 06:31 UTC
