### ISSUE TITLE
Markdown is not formatting correctly starting from v4.2.3

### ISSUE THREAD

**Issue by arman-g** [markedjs/marked#2735] opened 2023-02-15 22:34 UTC
**Marked version:**
v4.2.3 and later

**Describe the bug**
Some of the markdown is not formatting correctly (see the reproduce section below) starting from version 4.2.3. All the versions prior to that are formatting correctly.

**To Reproduce**
Please see the Marked Demo link below.

1. [Marked Demo](https://marked.js.org/demo/?text=Release%20Notes%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0AVer.%201.8.0%0A------%0A%3Cu%3ENew%20Features%3C%2Fu%3E%0A-%20In%20this%20release%20we%20have%20added%20an%20ability%20to%20organize%20confidential%20and%20sealed%20documents%20within%20groups%20(same%20as%20in%20TAP).%20The%20%3Cu%3EOrganize%20Confidential%2FSealed%20Documents%3C%2Fu%3E%20popup%20view%20can%20be%20accessed%20by%20clicking%20!%5BLock%20Icon%5D(%2Frelease-content%2Flock-icon.png)!%5BSeal%20Icon%5D(%2Frelease-content%2Fseal-icon.png)%20icons%20or%20the%20%3Cu%3EOrganize%3C%2Fu%3E%20button%20(see%20the%20images%20below).%3Cbr%3E%3Cbr%3E%0A%3Cspan%20class%3D%22image-wrap%22%3E!%5BGrouping%201%5D(%2Frelease-content%2Fgrouping-1.png)%20%26nbsp%3B%26nbsp%3B%3C%2Fspan%3E%0A!%5BGrouping%202%5D(%2Frelease-content%2Fgrouping-2.png)%0A%0A%3Cu%3EImprovements%3C%2Fu%3E%0A-%20Improved%20assembled%20transcript%20documents%27%20bookmarks.%20Now%2C%20the%20source%20documents%20are%20listed%20under%20their%20respective%20volumes%20(see%20the%20image%20below).%3Cbr%3E%3Cbr%3E%0A!%5BPDF%20Bookmarks%5D(%2Frelease-content%2Fpdf-bookmarks.png)%3Cbr%3E%3Cbr%3E%0A-%20Replaced%20the%20reporter%20transcript%20record%20%3Cu%3Epopup%20view%27s%3C%2Fu%3E%20%3Cu%3Edocument%3C%2Fu%3E%20dropdown-box%20with%20a%20list-box%20(UI).%20This%20will%20allow%20the%20user%20acting%20on%20multiple%20documents%20at%20the%20same%20time.%0A-%20In%20conjunction%20with%20this%20release%2C%20we%20also%20release%20an%20update%20to%20the%20transcript%20assembly%20component%20to%20lift%20the%202GB%20restriction%20for%20%3Cu%3Eresulting%20transcript%20documents%3C%2Fu%3E.%20Now%2C%20the%20size%20limit%20depends%20on%20the%20underlying%20system%2Fenvironment%20eCART%20is%20running.%0A--------------------------&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.2.3)
2. 

**Expected behavior**
Should format the markdown correctly.

**Comment by UziTech** [comment] 2023-02-16 01:34
Looks like this was broke by #2655

**Comment by UziTech** [comment] 2023-02-16 01:37
This can be easily fixed by formatting the markdown correctly. Block level elements should have a blank line above and below them. Adding a blank line above the bottom line fixes it. [demo](https://marked.js.org/demo/?text=Release%20Notes%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0AVer.%201.8.0%0A------%0A%3Cu%3ENew%20Features%3C%2Fu%3E%0A-%20In%20this%20release%20we%20have%20added%20an%20ability%20to%20organize%20confidential%20and%20sealed%20documents%20within%20groups%20(same%20as%20in%20TAP).%20The%20%3Cu%3EOrganize%20Confidential%2FSealed%20Documents%3C%2Fu%3E%20popup%20view%20can%20be%20accessed%20by%20clicking%20!%5BLock%20Icon%5D(%2Frelease-content%2Flock-icon.png)!%5BSeal%20Icon%5D(%2Frelease-content%2Fseal-icon.png)%20icons%20or%20the%20%3Cu%3EOrganize%3C%2Fu%3E%20button%20(see%20the%20images%20below).%3Cbr%3E%3Cbr%3E%0A%3Cspan%20class%3D%22image-wrap%22%3E!%5BGrouping%201%5D(%2Frelease-content%2Fgrouping-1.png)%20%26nbsp%3B%26nbsp%3B%3C%2Fspan%3E%0A!%5BGrouping%202%5D(%2Frelease-content%2Fgrouping-2.png)%0A%0A%3Cu%3EImprovements%3C%2Fu%3E%0A-%20Improved%20assembled%20transcript%20documents%27%20bookmarks.%20Now%2C%20the%20source%20documents%20are%20listed%20under%20their%20respective%20volumes%20(see%20the%20image%20below).%3Cbr%3E%3Cbr%3E%0A!%5BPDF%20Bookmarks%5D(%2Frelease-content%2Fpdf-bookmarks.png)%3Cbr%3E%3Cbr%3E%0A-%20Replaced%20the%20reporter%20transcript%20record%20%3Cu%3Epopup%20view%27s%3C%2Fu%3E%20%3Cu%3Edocument%3C%2Fu%3E%20dropdown-box%20with%20a%20list-box%20(UI).%20This%20will%20allow%20the%20user%20acting%20on%20multiple%20documents%20at%20the%20same%20time.%0A-%20In%20conjunction%20with%20this%20release%2C%20we%20also%20release%20an%20update%20to%20the%20transcript%20assembly%20component%20to%20lift%20the%202GB%20restriction%20for%20%3Cu%3Eresulting%20transcript%20documents%3C%2Fu%3E.%20Now%2C%20the%20size%20limit%20depends%20on%20the%20underlying%20system%2Fenvironment%20eCART%20is%20running.%0A%0A--------------------------&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.2.3)

**Comment by arman-g** [comment] 2023-02-16 02:14
> This can be easily fixed by formatting the markdown correctly. Block level elements should have a blank line above and below them. Adding a blank line above the bottom line fixes it. [demo](https://marked.js.org/demo/?text=Release%20Notes%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0AVer.%201.8.0%0A------%0A%3Cu%3ENew%20Features%3C%2Fu%3E%0A-%20In%20this%20release%20we%20have%20added%20an%20ability%20to%20organize%20confidential%20and%20sealed%20documents%20within%20groups%20(same%20as%20in%20TAP).%20The%20%3Cu%3EOrganize%20Confidential%2FSealed%20Documents%3C%2Fu%3E%20popup%20view%20can%20be%20accessed%20by%20clicking%20!%5BLock%20Icon%5D(%2Frelease-content%2Flock-icon.png)!%5BSeal%20Icon%5D(%2Frelease-content%2Fseal-icon.png)%20icons%20or%20the%20%3Cu%3EOrganize%3C%2Fu%3E%20button%20(see%20the%20images%20below).%3Cbr%3E%3Cbr%3E%0A%3Cspan%20class%3D%22image-wrap%22%3E!%5BGrouping%201%5D(%2Frelease-content%2Fgrouping-1.png)%20%26nbsp%3B%26nbsp%3B%3C%2Fspan%3E%0A!%5BGrouping%202%5D(%2Frelease-content%2Fgrouping-2.png)%0A%0A%3Cu%3EImprovements%3C%2Fu%3E%0A-%20Improved%20assembled%20transcript%20documents%27%20bookmarks.%20Now%2C%20the%20source%20documents%20are%20listed%20under%20their%20respective%20volumes%20(see%20the%20image%20below).%3Cbr%3E%3Cbr%3E%0A!%5BPDF%20Bookmarks%5D(%2Frelease-content%2Fpdf-bookmarks.png)%3Cbr%3E%3Cbr%3E%0A-%20Replaced%20the%20reporter%20transcript%20record%20%3Cu%3Epopup%20view%27s%3C%2Fu%3E%20%3Cu%3Edocument%3C%2Fu%3E%20dropdown-box%20with%20a%20list-box%20(UI).%20This%20will%20allow%20the%20user%20acting%20on%20multiple%20documents%20at%20the%20same%20time.%0A-%20In%20conjunction%20with%20this%20release%2C%20we%20also%20release%20an%20update%20to%20the%20transcript%20assembly%20component%20to%20lift%20the%202GB%20restriction%20for%20%3Cu%3Eresulting%20transcript%20documents%3C%2Fu%3E.%20Now%2C%20the%20size%20limit%20depends%20on%20the%20underlying%20system%2Fenvironment%20eCART%20is%20running.%0A%0A--------------------------&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.2.3)

That worked well, thanks!

**Comment by calculuschild** [comment] 2023-05-12 17:47
> This can be easily fixed by formatting the markdown correctly.

@UziTech is this working as intended then? Seems the issue occurred due to invalid syntax?

**Comment by UziTech** [comment] 2023-05-13 04:06
I think this is still technically a bug because it does not do the same thing as CommonMark even though the markdown is not well formatted.

**Comment by azmy60** [comment] 2023-05-17 14:37
Can I take this one?

**Comment by UziTech** [comment] 2023-05-17 21:39
@azmy60 sure

**Closed** 2023-05-30 22:21 UTC
Labels: L2 - annoying, category: lists, category: headings
