### ISSUE TITLE
Pass whole token to renderer to increase customization possibilities

### ISSUE THREAD

**Issue by GerkinDev** [markedjs/marked#2039] opened 2021-05-03 19:19 UTC
**What pain point are you perceiving?.**

I can't customize *marked* to handle custom syntax.

I'd like to add underline support to marked. I've customized the tokenizer to do what I want, but now, I'm stuck at the parser level, in which there is a hardcoded switch to extract props of the token and pass them to the renderer's method.

Since the parser is instanciated, as far as I can tell, from a static method (https://github.com/markedjs/marked/blob/6dda486f28b5429ce33491997351796af4e10da6/src/marked.js#L110 & https://github.com/markedjs/marked/blob/6dda486f28b5429ce33491997351796af4e10da6/src/Parser.js#L25-L28), I can't extend parser's capabilities by subclassing, only by modifying the prototype itself (and yet I'm not sure I could).

**Describe the solution you'd like**

I'd like to be able to add custom token types by subclassing the renderer, or using `marked.use`.

This could be done by passing the complete token and a reference to the parser instead of the switch I can't customize.
https://github.com/markedjs/marked/blob/6dda486f28b5429ce33491997351796af4e10da6/src/Parser.js#L200-L262

Something like `renderer[token.type](token, parser)`.

Then, the renderer would have the responsability to extract props from the token.

If this breaks the separation of concerns you desire, this may be still done at the parser's level, using a rules dictionary mapping token types to renderer calls.

**Comment by UziTech** [comment] 2021-05-03 20:16
duplicate of #2033

**Closed by UziTech** 2021-05-03 20:16 UTC
