### ISSUE TITLE
Code block immediately after list item not rendering

### ISSUE THREAD

**Issue by somebee** [markedjs/marked#1604] opened 2020-02-14 05:04 UTC
**Describe the bug**
If you add a code block immediately after a list item it will not render correctly. Ran into this in the real world when displaying issue comments from a github repository (the gh renderer deals with it as expected)

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=-%20List%20item%0A%60%60%60%0A%0A%3Cp%3ECode%3C%2Fp%3E%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=-%20List%20item%0A%60%60%60%0A%0A%3Cp%3ECode%3C%2Fp%3E%0A%60%60%60)

**Expected behavior**
See commonmark demo

**Comment by UziTech** [comment] 2020-02-14 07:15
PRs are welcome 😁

**Comment by UziTech** [comment] 2020-11-02 18:27
I'm going to close this issue as a duplicate of #1706 (even though this came first). That issue has a work around listed.

**Closed by UziTech** 2020-11-02 18:27 UTC
Labels: L2 - annoying, category: code blocks, category: lists
