### ISSUE TITLE
Awaiting the promise doesn’t work

### ISSUE THREAD

**Issue by babakfp** [markedjs/marked#2122] opened 2021-06-30 13:47 UTC
**Marked version:** 2.1.2
**[Shiki](https://github.com/shikijs/shiki) version:** 0.9.5

**Describe the bug**
I'm using Shiki for code syntax highlighting. The result of this code is `undefined` because it doesn't wait for the promise.

I wasn't able to fix it for 5, 6 days. So please help if you can❤

```js
renderer.code = (code, lang) => {
  shiki
  .getHighlighter({
    theme: 'nord',
  })
  .then(highlighter => {
    return highlighter.codeToHtml(code, lang)
  })
  .catch(error => console.log(error))
}
```

**To Reproduce**
[This is the project repo](https://github.com/babakfp/sv-docs).
related code is in this file `src/routes/docs/_sections.js`.

Full code
```js
import fs from 'fs'
import path from 'path'

import marked from 'marked'
import * as shiki from 'shiki'
import frontmatter from 'front-matter'

export default _ => {
	// Geting all files in "docs" folder
	const docs = fs.readdirSync('./content/docs', 'utf8')

	// Filtering out the files other than the `.md` extension
	const markdowns = docs.filter(
		// No empty file name
		filename => filename[0] !== '.' && path.extname(filename) === '.md'
	)

	// List of markdown files after doing some stuff on files
	return markdowns.map(filename => {
		// single markdown file
		const markdown = fs.readFileSync(`./content/docs/${filename}`, 'utf-8')

		// get the content as frontmatter object
		const markdownContent = frontmatter(markdown)

		const renderer = new marked.Renderer()

		renderer.code = (code, lang) => {
			shiki
				.getHighlighter({
					theme: 'nord',
				})
				.then(highlighter => {
					return highlighter.codeToHtml(code, lang)
				})
				.catch(error => console.log(error))
		}

		const html = marked(markdownContent.body, { renderer })
		console.log(`html ${html}`)

		return { html }
	})
}
```

**Comment by UziTech** [comment] 2021-06-30 16:00
Duplicate of #458

**Closed by UziTech** 2021-06-30 16:00 UTC

**Comment by UziTech** [comment] 2021-06-30 16:01
See https://marked.js.org/using_advanced#highlight for asyc highlighting

**Comment by babakfp** [comment] 2021-06-30 16:48
Thank you for your response.
I don't understand, what I'm doing wrong here?
@UziTech 

Code:
```js
marked.setOptions({
  highlight: (code, lang, callback) => {
    shiki
      .getHighlighter({ theme: 'nord' })
      .then(highlighter => {
        const result = highlighter.codeToHtml(code, lang)
        callback(null, result)
      })
      .catch(error => console.log(error))
  },
})
```

Error:
```terminal
TypeError: callback is not a function
  at C:\Users\babak\Desktop\STUFF\_Projects\_\SvelteKit\code\front\__sapper__\dev\server\server.js:82:5
```

**Comment by UziTech** [comment] 2021-06-30 19:00
you have to call marked with a callback

```js
marked(markdownString, (html) => {
  // marked is finished
})
```

looks like the docs need to be updated to include this.

**Comment by babakfp** [comment] 2021-06-30 19:45
I'm sorry but can you create a demo for me, please? It seems no matter what, I'm not able to make it work. Use a front-end framework and render a `.md` file with Marked and use [Shiki](https://github.com/shikijs/shiki) for the code highlighting. I'll be appreciated.
@UziTech

**Comment by UziTech** [comment] 2021-06-30 21:20
I've never used Shiki but here is what I would do

```js
const marked = require('marked');
const shiki = require('shiki');

function markdownToHtml(markdown) {

  const markedOptions = {
    highlight: (code, lang, callback) => {
      shiki
        .getHighlighter({ theme: 'nord' })
        .then(highlighter => {
          const result = highlighter.codeToHtml(code, lang)
          callback(null, result)
        })
        .catch(error => callback(error))
    },
  };

  const markedCallback = (err, html) => {
	  if (err) return reject(err);
	  resolve(html);
	};

  return new Promise((resolve, reject) => {
    marked(markdown, markedOptions, markedCallback);
  });
}

console.log(await markdownToHtml(markdown));
```

Haven't tested it but it shouldn't be hard for you to fix any issues.

**Comment by babakfp** [comment] 2021-07-01 01:38
Thank you for your help. It worked with a basic NodeJS app, but I replicated the same in my project and didn't work. No worry. It doesn't even worth my time to work on this project.
Thanks again for the help❤❤
@UziTech

**Comment by babakfp** [comment] 2022-11-04 17:19
Hey
So, a year later I tried out [this code](https://github.com/markedjs/marked/issues/2122#issuecomment-871735769) in another project and it worked.
Thanks
