### ISSUE TITLE
The Chinese colon broke sibling parsing

### ISSUE THREAD

**Issue by yunyuyuan** [markedjs/marked#2765] opened 2023-03-28 01:50 UTC
**Marked version:**
master

**Describe the bug**
![image](https://user-images.githubusercontent.com/45785585/228105614-74d8a57c-6395-463a-bacd-36f10dfdd77c.png)

**To Reproduce**

[Marked Demo](https://marked.js.org/demo/?text=*%5Bmarked%5D(https%3A%2F%2Fmarked.js.org%2F)*%3Amarkedjs%0A%0A*%5Bmarked%5D(https%3A%2F%2Fmarked.js.org%2F)*%EF%BC%9Amarkedjs&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**
Chinese colon be parsed fine.

**Comment by UziTech** [comment] 2023-03-28 14:44
Duplicate of #2531

**Closed by UziTech** 2023-03-28 14:44 UTC
