### ISSUE TITLE
UMD wrapper doesn't define correctly

### ISSUE THREAD

**Issue by PitPik** [markedjs/marked#1345] opened 2018-09-27 07:51 UTC
**Describe the bug**
```define(function() { return marked; });``` is actually just doing a ```require()``` as the first argument is the factory function.

**To Reproduce**
Try to require('marked') using requireJS

**Expected behavior**
```require('marked', marked => {});``` Should return the required library "marked".

**Solution**
```define('marked', [], function() { return marked; });```

Cheers

**Comment by styfle** [comment] 2018-09-27 13:01
Hi Peter, thanks for the bug report!

Can you setup a jsfiddle/jsbin so we can reproduce this issue?

Related: #1292

**Comment by UziTech** [comment] 2018-09-27 15:41
related: #372

**Comment by UziTech** [comment] 2018-09-27 15:46
I'm going to close this as a duplicate of #373 

If you want to add support for this feature that would be the place to comment.

**Closed by UziTech** 2018-09-27 15:46 UTC
