### ISSUE TITLE
Create a new instance from marked

### ISSUE THREAD

**Issue by SDVII** [markedjs/marked#2315] opened 2021-12-09 10:08 UTC
**Describe the feature**
Currently, or at least as far as I researched, in order to override the `renderer` and `walkTokens` you need to register them via `marked.use()`. However, this applies the overrides globally, which could be problematic in case you want to parse markdown differently from one use case to another.

Another option would be to provide a method to clear custom changes.

**Why is this feature necessary?**
It's necessary in case there are different classes using the marked with different overrides.

**Describe alternatives you've considered**
I am currently resetting all my rules by using `setOptions()` every time. EX:
```js
static makeHTML(markdown: string): string {
        marked.use({
            gfm: true,
            breaks: true,
            renderer: {
                paragraph(text) {
                    ....
                },
            },
            walkTokens: (token) => {
                ....
            }
        });

        const html = marked.parse(markdown);

        marked.setOptions({
            gfm: true,
            breaks: true,
            renderer: null,
            walkTokens: null,
        });

        return html;
}
```

**Comment by UziTech** [comment] 2021-12-09 14:42
Duplicate of #907.

If you want to submit a PR. That would be helpful. 😁👍

**Closed by UziTech** 2021-12-09 14:42 UTC
