### ISSUE TITLE
Support highlighting codespan using highlight option + or support async function in Renderer

### ISSUE THREAD

**Issue by aminya** [markedjs/marked#1780] opened 2020-10-17 03:00 UTC
**Describe the feature**
1) Currently, marked only allows specifying a highlight function for code blocks and not inline code (codespan). 

2) Using the custom Renderer is not possible because `(new Renderer()).codespan` does not accept async functions. Thus, there is no way to use an async highlighter for highlighting codespan unless an exoteric solution like [deasync](https://github.com/abbr/deasync) is used. 

**Why is this feature necessary?**
To highlight inline code. 

**Describe alternatives you've considered**
Using a Pandoc renderer. However, `lang` can be provided externally through other parts of the code, and so this is independent of supporting [Pandoc syntax](https://stackoverflow.com/a/25058886/7910299) for giving the language through the markdown syntax.

**Comment by UziTech** [comment] 2020-10-17 03:11
duplicate of #458 PRs are welcome 😁

**Closed by UziTech** 2020-10-17 03:11 UTC

**Comment by aminya** [comment] 2020-10-17 03:39
Well, this had two sections. The first one can be simpler I think since the highlight function already exists for `code`.

**Comment by UziTech** [comment] 2020-10-17 05:24
The issue with highlighting codespans is that you can't tell marked what language it is because there can't be an infostring like a code block.

You could always do the highlighting after running the markdown through marked.

**Comment by aminya** [comment] 2020-10-17 05:40
I can by using a lambda. For example, here I don't care about "lang" at all. I just supply my own "scopeName" (language)

https://github.com/atom-ide-community/atom-ide-markdown-service/blob/d02dce38781de4d1a71a0e3c84c0c146aff5f49c/src/renderer.ts#L72

**Comment by UziTech** [comment] 2020-10-17 06:00
You could use a [walkTokens](https://marked.js.org/using_pro#walk-tokens) function:

```js
const walkTokens = (token) => {
  if (token.type === 'codespan') {
    token.text = highlight(token.text);
  }
};

marked.use({ walkTokens });
```

For an async walk tokens function you will have to await all of the promises.

```js
const tokens = marked.lexer(md, opts);
const promises = [];
marked.walkTokens(tokens, (token) => {
	promises.push(asyncFunction(token));
});
await Promise.all(promises);
const html = marked.parser(tokens, opts);
```
