### ISSUE TITLE
Return `HTMLElement` from marked renderer

### ISSUE THREAD

**Issue by tokitou-san** [markedjs/marked#2932] opened 2023-08-10 02:31 UTC
**Marked version:**
```json
"marked": "^7.0.1",
```
**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

## Expectation

Return a `HTMLElement` instead `string` from marked renderer ( **code** ) for more styling.
eg:
```js
renderer: {
    code(code, language, isEscaped) {
        return <CodeBlock {code} {language} />
    },
},
```
## Result

![Screenshot from 2023-08-10 07-54-20](https://github.com/markedjs/marked/assets/114811070/0c95c686-0854-4f87-ad15-30f3890f3f53)

## What was attempted

I tried to return a `component` instead `string` from renderer, but showing typescript errors.
And this isnt working either ( returning string itself ):
```js
code(code, language, isEscaped) {
    return `<CodeBlock code=${code} language=${language} />`
},
```

**Comment by tokitou-san** [comment] 2023-08-10 02:32
Full code:
```svelte
<script lang="ts">
    import { emojis } from "$data/emojis";
    import { sanitize } from "$functions/sanitize";
    import hljs from "highlight.js";
    import "highlight.js/scss/github-dark.scss";
    import { Marked } from "marked";
    import type { MarkedEmojiOptions } from "marked-emoji";
    import { markedEmoji } from "marked-emoji";
    import { markedHighlight } from "marked-highlight";
    import { mangle } from "marked-mangle";
    import { CodeBlock } from "@skeletonlabs/skeleton";

    export let markdown = "";
    export { klass as class };

    let klass = "";

    // Override function

    const marked = new Marked(
        // Highlight.js
        markedHighlight({
            langPrefix: "hljs language-",
            highlight: (code, lang) => {
                const language = hljs.getLanguage(lang) ? lang : "plaintext";
                return hljs.highlight(code, { language }).value;
            }
        }),
        // Emoji plugin
        markedEmoji({
            emojis,
            unicode: false
        }),
        {
            extensions: [
                {
                    name: "emoji",
                    renderer: (token) => {
                        return `<img class="inline-flex w-4 justify-center align-center -translate-y-0.5 md:w-[1vw]" alt="${token.name}" src="${token.emoji}">`;
                    }
                }
            ]
        },
        // Mangle plugin
        mangle(),
        // Marked defaults
        {
            renderer: {
                del(text: string) {
                    return `<del class='unstyled'>${text}</del>`;
                },
                code(code, language, isEscaped) {
                    return <CodeBlock {code} {language} />
                },
            },
            // We dont need github like header prefix
            headerIds: false
        }
    );

    let promise_html: Promise<string>;
    $: promise_html = sanitize(marked.parse(markdown));
</script>

{#await promise_html then html}
    <markdown class={klass}>
        {@html html}
    </markdown>
{/await}
```

**Comment by UziTech** [comment] 2023-08-10 04:29
duplicate of #2915

**Closed by UziTech** 2023-08-10 04:29 UTC
