### ISSUE TITLE
Multiple extensions in `marked.use()` causing defaults being wrongly overrided

### ISSUE THREAD

**Issue by hyrious** [markedjs/marked#2649] opened 2022-11-11 08:26 UTC
**Marked version:**
4.2.2

**Describe the bug**
As described in the [pro doc](https://marked.js.org/using_pro#use):

- The `renderer` and `tokenizer` options are objects with functions that will be merged into the built-in `renderer` and `tokenizer` respectively.

Which means people can use multiple extensions written in this way:

```js
marked.use({ renderer }, { tokenizer })
```

However this way will cause errors, see reproduction below.

**To Reproduce**
Install marked locally and run this simple script:

```js
import { marked } from "marked";

marked.use({ tokenizer: {} }, { renderer: {} });
marked.parse(`# hello`);
```

yields:

```js
TypeError: renderer.text is not a function
```

**Workarounds**
You can call `marked.use()` multiple times to avoid this error.

**Expected behavior**
No error occurs.

**Cause**
The last line of `marked.use()`
https://github.com/markedjs/marked/blob/fdbbec699f40d652dd7c8b9ac50c5cbaed75776e/src/marked.js#L263
causes an unexpected `renderer` or `tokenizer` object being merged into `marked.defaults`.

Maybe related(?) #2082

**Comment by UziTech** [comment] 2022-11-11 08:45
It looks like the issue is this line

https://github.com/markedjs/marked/blob/fdbbec699f40d652dd7c8b9ac50c5cbaed75776e/src/marked.js#L156

currently it merges all of the extensions together to get the options. It should be smarter about how it merges the options.

For example, if one extension has `async: true` set and another one after it has `async: false` the last extension loaded will override the previous which is what we want for most options but not all. in the case of `async` if any of the extensions are `async: true` than `async` should be `true`.

It should also disregard the `renderer`, `tokenizer`, `extensions`, and `walkTokens` options in this merge. They are merged intelligently below this line.

There might be some other options that I am missing.

**Closed** 2022-11-20 16:06 UTC
Labels: L2 - annoying
