### ISSUE TITLE
The lexer appears to handle new lines incorrectly 

### ISSUE THREAD

**Issue by phillipb** [markedjs/marked#2340] opened 2021-12-30 20:33 UTC
**Marked version:**
4.0.6

**Describe the bug**
When using the lexer, it ignores new lines under some circumstances. 

**To Reproduce**
```
console.log(marked.lexer("\nT\nh\n---"))
```
returns 
```json
[
    {
        "type": "paragraph",
        "raw": "T\nh",
        "text": "T\nh",
        "tokens": [
            {
                "type": "text",
                "raw": "T\nh",
                "text": "T\nh"
            }
        ]
    },
    {
        "type": "hr",
        "raw": "---"
    }
]
```

As you can see, there's a missing spacer for the new line before the `hr` type.

Here's a demo: https://marked.js.org/demo/?outputType=lexer&text=t%0Ah%0A----&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

**Expected behavior**
```json
[
    {
        "type": "paragraph",
        "raw": "T\nh",
        "text": "T\nh",
        "tokens": [
            {
                "type": "text",
                "raw": "T\nh",
                "text": "T\nh"
            }
        ]
    },
    {
        "type": "spacer",
        "raw": "\n"
    },
    {
        "type": "hr",
        "raw": "---"
    }
]
```

The issue seems to be here: https://github.com/markedjs/marked/blob/939689641817659998f63ce61ae76f0e57343268/src/Tokenizer.js#L76. 

Is there a reason we ignore spaces that are one character?

**Comment by UziTech** [comment] 2021-12-30 20:47
Duplicate of https://github.com/markedjs/marked/issues/2134#issuecomment-883886650

If you would like to work on removing that and getting all the tests to pass it would be much appreciated. 😁 👍

**Closed** 2022-01-06 15:31 UTC
