### ISSUE TITLE
 Private identifiers are only available when targeting ECMAScript 2015 and higher.

### ISSUE THREAD

**Issue by sreejithkalarikkal** [markedjs/marked#3075] opened 2023-11-06 07:31 UTC
**9.1.2**

**Describe the bug**
I made a code using typescript on executing the script  mdx file will be converted to HTML.
The script used is  npx tsc ./htmltest/mrkdowntohtml.ts
I used the marked package to convert my mdx file or md file to html.
While running the script i am getting an error as 
node_modules/.pnpm/marked@9.1.5/node_modules/marked/lib/marked.d.ts:432:2 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

I searched the net for a solution and applied the changes but not worked

**To Reproduce**
[mrkdowntohtml.zip](https://github.com/markedjs/marked/files/13263707/mrkdowntohtml.zip)
1)Unzip the attached typescript file 
2)Run the script using the command  npx tsc ./htmltest/mrkdowntohtml.ts from the terminal

**Expected behavior**

**Comment by UziTech** [comment] 2023-11-06 15:17
Duplicate of #2925

**Closed by UziTech** 2023-11-06 15:17 UTC
