### ISSUE TITLE
Italic does not work correctly with double quotes

### ISSUE THREAD

**Issue by devoto13** [markedjs/marked#1672] opened 2020-05-11 21:09 UTC
**Describe the bug**
See Marked Demo. If I remove "" (quotes), then italic section is correctly recognised.

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=For%20the%20question%20*%22Which%3F%22*%2C%20we%20need%20to%20choose%20all%20which%20are%20*not*%20loaded.&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=For%20the%20question%20*%22Which%3F%22*%2C%20we%20need%20to%20choose%20all%20which%20are%20*not*%20loaded.)

**Expected behavior**
See CommonMark Demo.

**Comment by UziTech** [comment] 2020-05-12 06:01
duplicate of #1358

**Closed by UziTech** 2020-05-12 06:01 UTC
