### ISSUE TITLE
CDN src URI

### ISSUE THREAD

**Issue by andrew-rogers** [markedjs/marked#2285] opened 2021-11-13 08:46 UTC
https://github.com/markedjs/marked/blob/92da674fcec0491defdd1f604d805df95f680fb1/README.md?plain=1#L69

I get "Uncaught ReferenceError: exports is not defined" error message on the console. I had to change the script src tag to the below to make this demo work.

<script src="https://cdn.jsdelivr.net/gh/markedjs/marked/marked.min.js"></script>

**Comment by UziTech** [comment] 2021-11-13 16:54
Duplicate of #2282

**Closed by UziTech** 2021-11-13 16:54 UTC
