### ISSUE TITLE
Emphasis with Asterisk doesn't work when followed by quotation mark

### ISSUE THREAD

**Issue by kunizial** [markedjs/marked#1413] opened 2019-01-25 12:00 UTC
## Expectation

**CommonMark Demo:** [demo](https://spec.commonmark.org/dingus/?text=*%22test%22*)

Using asterisks for emphasis for a quote starting with a quotation mark.

## Result

**Marked Demo:** [demo](https://marked.js.org/demo/?text=*%22test*&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)

The asterisks aren't parsed as emphasis and instead left as-is.

## What was attempted

Works with underscore for emphasis: [demo](https://marked.js.org/demo/?text=_%22test_&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)

**Comment by UziTech** [comment] 2019-02-19 17:41
closing as duplicate of #1358

**Closed by UziTech** 2019-02-19 17:41 UTC
Labels: L2 - annoying, category: inline elements
