### ISSUE TITLE
Some markdown elements not parsed for content with inline html

### ISSUE THREAD

**Issue by mjbvz** [markedjs/marked#1195] opened 2018-04-02 22:38 UTC
**Marked version:** 0.3.19

**Markdown flavor:** CommonMark

## Expectation

Rendering the markdown:

```md
<table>
</table>
<br>

## h1

1. a
1. **b**

<table>
</table>
```

## Result
Heading and list not parsed. Here's the html output:

```html
<table>
</table>
<br>

## h1

1. a
1. <strong>b</strong>

<table>
</table>
```

**Comment by UziTech** [comment] 2018-04-03 17:53
Looks like the problem is in the [html regex](https://github.com/markedjs/marked/blob/9a52de7a2c633b4004c368ea74fb523d0d17ee8c/lib/marked.js#L23)

```
...closed *(?:\n{2,}|\s*$)...
```

says there must to be 2 `\n` after a closing tag or just white space. 

This apparently has to do with the common mark [example \#199](https://spec.commonmark.org/0.28/#example-119)

**Comment by joshbruce** [comment] 2018-04-04 02:29
#985

**Closed** 2018-04-10 20:24 UTC
Labels: L2 - annoying
