### ISSUE TITLE
Marked(string) Always retorning [object object]

### ISSUE THREAD

**Issue by gabrielpereiraa** [markedjs/marked#3389] opened 2024-08-02 18:50 UTC
Marked version: 13.0.2

**Describe the bug**
Marked(string) Always retorning [object object]

had to downgrade to version 12.0.0 to make it work

**Comment by simonMoisselin** [comment] 2024-08-02 22:32
Same for listitem

**Comment by UziTech** [comment] 2024-08-03 01:58
If you give us code to reproduce the error we can try to help.

**Comment by HearseDev** [comment] 2024-08-03 04:53
```const md = marked.parse(markdown) as string
print(md) // will return [object object]```

**Comment by UziTech** [comment] 2024-08-03 14:26
It works for me with the latest version of marked-gfm-heading-id

**Comment by rsivan** [comment] 2024-08-13 18:07
This should be considered **critical**, as all of angular.dev is showing unprocessed links.
See for example [https://angular.dev/essentials/components#using-a-component](https://angular.dev/essentials/components#using-a-component)

**Comment by UziTech** [comment] 2024-08-14 03:09
@rsivan Looks like that is fixed in https://github.com/angular/angular/pull/57377

**Closed** 2024-08-21 04:03 UTC
Labels: need more info
