### ISSUE TITLE
When the blank lines in the code block, the conversion fails

### ISSUE THREAD

**Issue by aaaaaajie** [markedjs/marked#2348] opened 2022-01-05 05:55 UTC
**Marked version:** 3.0.2

**Describe the bug**
When the list and the code block are together(blank lines in the code block), the conversion fails, source code as shown
![image](https://user-images.githubusercontent.com/36189354/148167270-d175ea2c-1732-4622-95b1-1d24fca5dbb8.png)
After the conversion is like this:
![image](https://user-images.githubusercontent.com/36189354/148167308-f51b26c1-1509-4dda-83b9-e0f00a4b9a3a.png)

**To Reproduce**

**Expected behavior**
![image](https://user-images.githubusercontent.com/36189354/148167498-38eef7d5-496a-4f6e-bcbd-8ad5ea788b1d.png)

**Comment by UziTech** [comment] 2022-01-05 15:40
duplicate of #1590

**Closed by UziTech** 2022-01-05 15:40 UTC
