### ISSUE TITLE
Error: renderer 'options' does not exist

### ISSUE THREAD

**Issue by doroved** [markedjs/marked#3127] opened 2023-12-08 06:55 UTC
**Marked version:**
11.0.0

**Describe the bug**
In version 10.0.0 everything is fine, after upgrading to 11.0.0 an error occurs in this line `marked.use({ renderer })`
What is the problem? No TS errors
<img width="573" alt="image" src="https://github.com/markedjs/marked/assets/30116541/fe4d25fd-6d90-4924-a7da-d13f988f5ea6">

**Comment by UziTech** [comment] 2023-12-08 07:16
Duplicate of #3117 will be fixed by #3118

**Closed by UziTech** 2023-12-08 07:16 UTC
