### ISSUE TITLE
character "<, >, &" will be translated into &lt; &gt; &amp;

### ISSUE THREAD

**Issue by poberwong** [markedjs/marked#779] opened 2016-08-01 06:31 UTC
Anyone can tell me how to resolve it ? I just wanna show the characters correctly not its translation code in code-block

**Comment by Feder1co5oave** [comment] 2016-08-07 16:55
Are you using `sanitize: true` as an option?
Provide some sample input and expected output, please.

**Comment by adam-lynch** [comment] 2016-08-14 00:00
Possible duplicate of #529

**Comment by hojas** [comment] 2016-10-24 06:34
`sanitize` can not control this.

**Comment by bholt** [comment] 2016-11-03 19:04
The problem I'm seeing is that the sanitization is happening incorrectly for code blocks specifically, so "&" works fine and shows up as "&", but "`` `&` ``" renders as "`&amp;`". Obviously I don't want to disable sanitize, I just want code blocks to de-sanitize.

This seems related to #287 which was never addressed.

**Comment by Feder1co5oave** [comment] 2018-01-25 20:27
Ampersand is a special character in html, so it must be escaped as an entity reference as `&amp;`

**Comment by joshbruce** [comment] 2018-01-25 22:02
```
& < >
```

**Comment by joshbruce** [comment] 2018-01-25 22:03
Given that small test - and it being scoped to code blocks, we might actually have something here. Believe HTML looks at the contents of code blocks differently.

**Comment by barthel** [comment] 2018-01-26 09:56
The GFM definition of github about `<` in  code-blocks including two examples: https://github.github.com/gfm/#fenced-code-blocks

Outside of code-blocks `<` should be escaped like `\<` and transformed into `&lt;`: https://github.github.com/gfm/#backslash-escapes

**Comment by joshbruce** [comment] 2018-01-26 14:44
@barthel: Thanks for the reference. That's interesting because the GFM examples have the lt and gt being converted to the unicode-like designation. But GitHub itself doesn't seem to escape them. 

Weird. Am I missing something??

**Comment by Mathieudewet** [comment] 2018-06-01 08:41
I had the same issue but figuring out that happened only with backticks but working with tildes
For instances:

```
string <string>string
```

doesnt work, while:

~~~
string <string>string
~~~

Works like a charm.

**Comment by wwkimball** [comment] 2018-10-14 05:47
Just dropping a note of support for this issue.  I was gearing one of my sites up to use marked.js (with highlight.js) until I ran into this.  For education materials, I need to share blocks of Ruby and Puppet code where symbols like `=>` are **very often** used.  With this bug, my sample code blocks render very poorly, making them impossible to read.

*The issue appears to be possible double-handling of `&`*.  For example, when `=>` is encountered within a code-block, it is converted to `=&gt;`, which might be fine on its own.  However, the resulting value appears to then be re-processed *again* into `=&amp;gt;`.  That second handling is the problem.

I did find a viable workaround, however.  In order to incorporate highlight.js, I evidently had to write some custom renderer code for marked.js, so I took guidance from [Shuhei Kagawa](https://shuheikagawa.com/blog/2015/09/21/using-highlight-js-with-marked/).  Because I was already customizing the HTML output to add CSS style hints for highlight.js, I took the same opportunity to fix the broken `&amp;`s.  Note that the following code is significantly different from Shuhei's because I'm still required to support Internet Explorer users (yes, it's painful and yes, it's reality) along with all the latest browsers.

My workaround to this problem (and the problem of making marked.js and highlight.js play nicely together with CSS):

```javascript
// With guidance from https://shuheikagawa.com/blog/2015/09/21/using-highlight-js-with-marked/
const marked       = window.marked;
const highlightjs  = window.hljs;
const hljsRenderer = new marked.Renderer();

hljsRenderer.code = function(block, lang) {
    // Colorize the block only if the language is known to highlight.js
    var realLang = ((null == lang) ? 'plaintext' : lang);
    var colorized = !!(realLang && highlightjs.getLanguage(realLang))
        ? highlightjs.highlight(realLang, block).value
        : block
    ;
    return '<pre rel="' + realLang + '">' + "\n"
        + '<code class="hljs ' + realLang + '">'
        + colorized.replace(/&amp;/g, '&')
        + '</code>' + "\n"
        + '</pre>'
    ;
};

// Set the renderer to marked
marked.setOptions({
    renderer: hljsRenderer
});

// Monkey in String.trimStart() support for browsers that don't support it
String.prototype.trimStart = String.prototype.trimStart || function() {
    return this.replace(/^\s+/, '');
}

// Render Markdown-formatted publications as HTML
document.getElementById('publication_body').innerHTML =
    marked(
        document.getElementById('publication_body').innerHTML.trimStart()
    );
```

Bonus:  The code above enabled me to display the code language above every code-block via CSS, like:

```css
pre[rel]::before {
    text-transform: capitalize;
    font-size: 0.75em;
    content: attr(rel);
    color: white;
}
```

**Comment by styfle** [comment] 2018-10-15 13:04
> The issue appears to be possible double-handling of `&`. For example, when `=>` is encountered within a code-block, it is converted to `=&gt;`, which might be fine on its own. However, the resulting value appears to then be re-processed again into `=&amp;gt;`. That second handling is the problem.

I'm glad you found a workaround!

However, I am not seeing this issue with the default settings in marked.

[Example markdown](https://marked.js.org/demo/?outputType=html&text=%23%23%20Paragraph%0A%0AThis%20is%20a%20less%20than%20%3C%0AThis%20is%20a%20greater%20than%20%3E%0AThis%20is%20a%20arrow%20%3D%3E%0A%0A%23%23%20Code%0A%0A%60%60%60js%0AThis%20is%20a%20less%20than%20%3C%0AThis%20is%20a%20greater%20than%20%3E%0AThis%20is%20a%20arrow%20%3D%3E%0A%60%60%60)

Perhaps you are using the `sanitize: true` option as others have mentioned.

I would suggest using a different sanitizer than the built-in one as discussed in #1232 
...in particular, [this comment](https://github.com/markedjs/marked/issues/1232#issuecomment-414308183)

**Comment by styfle** [comment] 2018-10-15 17:35
@wwkimball Thanks for the details, that makes sense 👍 

Since this issue doesn't have any steps to reproduce, I'm going to close it.

I'm going to reiterate for future readers, see #1232 for better `sanitize` options.

**Closed by styfle** 2018-10-15 17:35 UTC
Labels: L2 - annoying, category: code blocks

**Comment by mominrazashahid** [comment] 2023-01-26 09:35
I am also facing this issue using express sanitize any solution ?
